#!/usr/bin/env bash

go run github.com/openconfig/ygot/generator -path=yang -output_file=e2node_1_0_0/generated.go -package_name=e2node_1_0_0 -generate_fakeroot e2node@2020-05-01.yang



sedi=(-i)
case "$(uname)" in
  Darwin*) sedi=(-i "")
esac

lf=$'\n'; sed "${sedi[@]}" -e "1s/^/\/\/ Code generated by YGOT. DO NOT EDIT.\\$lf/" e2node_1_0_0/generated.go


