// Code generated by model-compiler. DO NOT EDIT.

// SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0

package api

import (
	"github.com/openconfig/gnmi/proto/gnmi"
)

var modelData = []*gnmi.ModelData{
	{Name: "onf-test1", Organization: "Open Networking Foundation", Version: "2019-06-10"},
	{Name: "onf-test1-augmented", Organization: "Open Networking Foundation", Version: "2020-02-29"},
}

var encodings = []gnmi.Encoding{gnmi.Encoding_JSON_IETF}

func ModelData() []*gnmi.ModelData {
	return modelData
}

func Encodings() []gnmi.Encoding {
	return encodings
}
