# SPDX-FileCopyrightText: 2022-present Intel Corporation
# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
components:
  parameters:
    target:
      content:
        text/plain; charset=utf-8:
          schema:
            type: string
      description: target (target in onos-config)
      in: path
      name: target
      required: true
  requestBodies:
    RequestBody_E2node:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/E2node'
    RequestBody_E2node_Intervals:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/E2node_Intervals'
  schemas:
    AdditionalPropertiesUnchTarget:
      description: both the additional property 'unchanged' and the 'target'
      properties:
        target:
          description: an override of the target (target)
          title: target
          type: string
        unchanged:
          description: A comma seperated list of unchanged mandatory attribute names
          title: unchanged
          type: string
      title: AdditionalPropertiesUnchTarget
      type: object
    AdditionalPropertyTarget:
      description: Optionally specify a target other than the default (only on PATCH
        method)
      properties:
        target:
          description: an override of the target (target)
          title: target
          type: string
      title: AdditionalPropertyTarget
      type: object
    AdditionalPropertyUnchanged:
      description: To optionally omit 'required' properties, add them to 'unchanged'
        list
      properties:
        unchanged:
          description: A comma seperated list of unchanged mandatory attribute names
          title: unchanged
          type: string
      title: AdditionalPropertyUnchanged
      type: object
    E2node:
      additionalProperties:
        $ref: '#/components/schemas/AdditionalPropertyTarget'
      description: The top level container
      properties:
        intervals:
          $ref: '#/components/schemas/E2node_Intervals'
      title: E2node
      type: object
    E2node_Intervals:
      description: Intervals for E2 services
      properties:
        PdcpMeasReportPerUe:
          description: Interval for report of PdcpMeasReportPerUe
          format: int32
          minimum: 0
          title: PdcpMeasReportPerUe
          type: integer
        RadioMeasReportPerCell:
          description: Interval for report of RadioMeasReportPerUe
          format: int32
          minimum: 0
          title: RadioMeasReportPerCell
          type: integer
        RadioMeasReportPerUe:
          description: Interval for report of RadioMeasReportPerUe
          format: int32
          minimum: 0
          title: RadioMeasReportPerUe
          type: integer
        SchedMeasReportPerCell:
          description: Interval for report of SchedMeasReportPerCell
          format: int32
          minimum: 0
          title: SchedMeasReportPerCell
          type: integer
        SchedMeasReportPerUe:
          description: Interval for report of SchedMeasReportPerUe
          format: int32
          minimum: 0
          title: SchedMeasReportPerUe
          type: integer
      title: E2node_Intervals
      type: object
info:
  contact:
    email: info@opennetworking.org
    name: Open Networking Foundation
    url: https://opennetworking.org
  description: OpenAPI 3 specification is generated from e2node onos-config model
    plugin
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  title: e2node-1.0.0
  version: 1.0.0
openapi: 3.0.0
paths:
  /e2node/v1.0.0/{target}/e2node:
    delete:
      operationId: deleteE2node
      responses:
        "200":
          description: DELETE 200 OK
      summary: DELETE /e2node
    description: The top level container
    get:
      operationId: getE2node
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/E2node'
          description: GET OK 200
      summary: GET /e2node Container
    parameters:
    - $ref: '#/components/parameters/target'
    post:
      operationId: postE2node
      requestBody:
        $ref: '#/components/requestBodies/RequestBody_E2node'
      responses:
        "201":
          description: created
      summary: POST /e2node
  /e2node/v1.0.0/{target}/e2node/intervals:
    delete:
      operationId: deleteE2node_Intervals
      responses:
        "200":
          description: DELETE 200 OK
      summary: DELETE /e2node/intervals
    description: Intervals for E2 services
    get:
      operationId: getE2node_Intervals
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/E2node_Intervals'
          description: GET OK 200
      summary: GET /e2node/intervals Container
    parameters:
    - $ref: '#/components/parameters/target'
    post:
      operationId: postE2node_Intervals
      requestBody:
        $ref: '#/components/requestBodies/RequestBody_E2node_Intervals'
      responses:
        "201":
          description: created
      summary: POST /e2node/intervals
