#!/usr/bin/env bash

mkdir -p aether_2_0_0

OPENCORD="${OPENCORD:-$HOME/git/opencord}"

go run github.com/openconfig/ygot/generator -path=$OPENCORD/roc-helm-charts/config-models/aether-2.0.x/files/yang \
       -output_file=aether_2_0_0/generated.go -package_name=aether_2_0_0 -generate_fakeroot --include_descriptions\
       onf-enterprise.yang onf-connectivity-service.yang


sedi=(-i)
case "$(uname)" in
  Darwin*) sedi=(-i "")
esac

lf=$'\n'; sed "${sedi[@]}" -e "1s/^/\/\/ Code generated by YGOT. DO NOT EDIT.\\$lf/" aether_2_0_0/generated.go
