models:
	go generate
	pyang -f tree yang/access-profile@2020-08-18.yang yang/apn-profile@2020-08-18.yang yang/qos-profile@2020-08-18.yang yang/up-profile@2020-08-18.yang yang/aether-subscriber@2020-10-22.yang  yang/ietf-inet-types@2013-07-15.yang yang/ietf-yang-types@2013-07-15.yang > aether.tree
