#!/usr/bin/env bash

go run github.com/openconfig/ygot/generator -path=yang -output_file=rbac_1_0_0/generated.go -package_name=rbac_1_0_0 -generate_fakeroot rbac@2020-08-10.yang



sedi=(-i)
case "$(uname)" in
  Darwin*) sedi=(-i "")
esac

lf=$'\n'; sed "${sedi[@]}" -e "1s/^/\/\/ Code generated by YGOT. DO NOT EDIT.\\$lf/" rbac_1_0_0/generated.go


