// Code generated by GENERATOR. DO NOT EDIT.
/*
Package enterprise_1_0_0 is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /home/smbaker/gopath/pkg/mod/github.com/openconfig/ygot@v0.6.1-0.20200103195725-e3c44fa43926/genutil/names.go
using the following YANG input files:
	- device-range@2020-11-18.yang
	- device-group@2020-11-18.yang
	- enterprise@2020-11-18.yang
	- site@2020-11-18.yang
	- use-case@2020-11-18.yang
	- deployment-environment@2020-11-18.yang
	- application@2020-11-18.yang
	- visibility@2020-11-18.yang
	- qos@2020-11-18.yang
Imported modules were sourced from:
	- yang/...
*/
package enterprise_1_0_0

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Application_Application represents the /application/application YANG schema element.
type Application_Application struct {
	Application	map[string]*Application_Application_Application	`path:"application" module:"application"`
}

// IsYANGGoStruct ensures that Application_Application implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Application_Application) IsYANGGoStruct() {}

// NewApplication creates a new entry in the Application list of the
// Application_Application struct. The keys of the list are populated from the input
// arguments.
func (t *Application_Application) NewApplication(Id string) (*Application_Application_Application, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Application == nil {
		t.Application = make(map[string]*Application_Application_Application)
	}

	key := Id

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Application[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Application", key)
	}

	t.Application[key] = &Application_Application_Application{
		Id: &Id,
	}

	return t.Application[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Application_Application) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Application_Application"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Application_Application) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Application_Application_Application represents the /application/application/application YANG schema element.
type Application_Application_Application struct {
	DeploymentEnvironment	*string	`path:"deployment-environment" module:"application"`
	Description	*string	`path:"description" module:"application"`
	DisplayName	*string	`path:"display-name" module:"application"`
	Endpoint	map[string]*Application_Application_Application_Endpoint	`path:"endpoint" module:"application"`
	Id	*string	`path:"id" module:"application"`
	Qos	map[string]*Application_Application_Application_Qos	`path:"qos" module:"application"`
}

// IsYANGGoStruct ensures that Application_Application_Application implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Application_Application_Application) IsYANGGoStruct() {}

// NewEndpoint creates a new entry in the Endpoint list of the
// Application_Application_Application struct. The keys of the list are populated from the input
// arguments.
func (t *Application_Application_Application) NewEndpoint(Name string) (*Application_Application_Application_Endpoint, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Endpoint == nil {
		t.Endpoint = make(map[string]*Application_Application_Application_Endpoint)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Endpoint[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Endpoint", key)
	}

	t.Endpoint[key] = &Application_Application_Application_Endpoint{
		Name: &Name,
	}

	return t.Endpoint[key], nil
}

// NewQos creates a new entry in the Qos list of the
// Application_Application_Application struct. The keys of the list are populated from the input
// arguments.
func (t *Application_Application_Application) NewQos(Qos string) (*Application_Application_Application_Qos, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Qos == nil {
		t.Qos = make(map[string]*Application_Application_Application_Qos)
	}

	key := Qos

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Qos[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Qos", key)
	}

	t.Qos[key] = &Application_Application_Application_Qos{
		Qos: &Qos,
	}

	return t.Qos[key], nil
}

// ΛListKeyMap returns the keys of the Application_Application_Application struct, which is a YANG list entry.
func (t *Application_Application_Application) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}

	return map[string]interface{}{
		"id": *t.Id,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Application_Application_Application) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Application_Application_Application"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Application_Application_Application) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Application_Application_Application_Endpoint represents the /application/application/application/endpoint YANG schema element.
type Application_Application_Application_Endpoint struct {
	Hostname	*string	`path:"hostname" module:"application"`
	Name	*string	`path:"name" module:"application"`
	Port	*uint16	`path:"port" module:"application"`
}

// IsYANGGoStruct ensures that Application_Application_Application_Endpoint implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Application_Application_Application_Endpoint) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Application_Application_Application_Endpoint struct, which is a YANG list entry.
func (t *Application_Application_Application_Endpoint) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Application_Application_Application_Endpoint) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Application_Application_Application_Endpoint"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Application_Application_Application_Endpoint) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Application_Application_Application_Qos represents the /application/application/application/qos YANG schema element.
type Application_Application_Application_Qos struct {
	Allowed	*bool	`path:"allowed" module:"application"`
	Qos	*string	`path:"qos" module:"application"`
}

// IsYANGGoStruct ensures that Application_Application_Application_Qos implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Application_Application_Application_Qos) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Application_Application_Application_Qos struct, which is a YANG list entry.
func (t *Application_Application_Application_Qos) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Qos == nil {
		return nil, fmt.Errorf("nil value for key Qos")
	}

	return map[string]interface{}{
		"qos": *t.Qos,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Application_Application_Application_Qos) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Application_Application_Application_Qos"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Application_Application_Application_Qos) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// DeploymentEnvironment_DeploymentEnvironment represents the /deployment-environment/deployment-environment YANG schema element.
type DeploymentEnvironment_DeploymentEnvironment struct {
	DeploymentEnvironment	map[string]*DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment	`path:"deployment-environment" module:"deployment-environment"`
}

// IsYANGGoStruct ensures that DeploymentEnvironment_DeploymentEnvironment implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DeploymentEnvironment_DeploymentEnvironment) IsYANGGoStruct() {}

// NewDeploymentEnvironment creates a new entry in the DeploymentEnvironment list of the
// DeploymentEnvironment_DeploymentEnvironment struct. The keys of the list are populated from the input
// arguments.
func (t *DeploymentEnvironment_DeploymentEnvironment) NewDeploymentEnvironment(Id string) (*DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.DeploymentEnvironment == nil {
		t.DeploymentEnvironment = make(map[string]*DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment)
	}

	key := Id

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.DeploymentEnvironment[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list DeploymentEnvironment", key)
	}

	t.DeploymentEnvironment[key] = &DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment{
		Id: &Id,
	}

	return t.DeploymentEnvironment[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *DeploymentEnvironment_DeploymentEnvironment) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["DeploymentEnvironment_DeploymentEnvironment"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *DeploymentEnvironment_DeploymentEnvironment) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment represents the /deployment-environment/deployment-environment/deployment-environment YANG schema element.
type DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment struct {
	ClusterName	*string	`path:"cluster-name" module:"deployment-environment"`
	Description	*string	`path:"description" module:"deployment-environment"`
	DisplayName	*string	`path:"display-name" module:"deployment-environment"`
	Id	*string	`path:"id" module:"deployment-environment"`
	Site	*string	`path:"site" module:"deployment-environment"`
}

// IsYANGGoStruct ensures that DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment struct, which is a YANG list entry.
func (t *DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}

	return map[string]interface{}{
		"id": *t.Id,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *DeploymentEnvironment_DeploymentEnvironment_DeploymentEnvironment) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Device represents the /device YANG schema element.
type Device struct {
	Application	*Application_Application	`path:"application" module:"application"`
	DeploymentEnvironment	*DeploymentEnvironment_DeploymentEnvironment	`path:"deployment-environment" module:"deployment-environment"`
	DeviceGroup	*DeviceGroup_DeviceGroup	`path:"device-group" module:"device-group"`
	DeviceRange	*DeviceRange_DeviceRange	`path:"device-range" module:"device-range"`
	Enterprise	*Enterprise_Enterprise	`path:"enterprise" module:"enterprise"`
	Qos	*Qos_Qos	`path:"qos" module:"qos"`
	Site	*Site_Site	`path:"site" module:"site"`
	UseCase	*UseCase_UseCase	`path:"use-case" module:"use-case"`
	Visibility	*Visibility_Visibility	`path:"visibility" module:"visibility"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// DeviceGroup_DeviceGroup represents the /device-group/device-group YANG schema element.
type DeviceGroup_DeviceGroup struct {
	DeviceGroup	map[string]*DeviceGroup_DeviceGroup_DeviceGroup	`path:"device-group" module:"device-group"`
}

// IsYANGGoStruct ensures that DeviceGroup_DeviceGroup implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DeviceGroup_DeviceGroup) IsYANGGoStruct() {}

// NewDeviceGroup creates a new entry in the DeviceGroup list of the
// DeviceGroup_DeviceGroup struct. The keys of the list are populated from the input
// arguments.
func (t *DeviceGroup_DeviceGroup) NewDeviceGroup(Id string) (*DeviceGroup_DeviceGroup_DeviceGroup, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.DeviceGroup == nil {
		t.DeviceGroup = make(map[string]*DeviceGroup_DeviceGroup_DeviceGroup)
	}

	key := Id

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.DeviceGroup[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list DeviceGroup", key)
	}

	t.DeviceGroup[key] = &DeviceGroup_DeviceGroup_DeviceGroup{
		Id: &Id,
	}

	return t.DeviceGroup[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *DeviceGroup_DeviceGroup) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["DeviceGroup_DeviceGroup"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *DeviceGroup_DeviceGroup) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// DeviceGroup_DeviceGroup_DeviceGroup represents the /device-group/device-group/device-group YANG schema element.
type DeviceGroup_DeviceGroup_DeviceGroup struct {
	Description	*string	`path:"description" module:"device-group"`
	DisplayName	*string	`path:"display-name" module:"device-group"`
	Id	*string	`path:"id" module:"device-group"`
}

// IsYANGGoStruct ensures that DeviceGroup_DeviceGroup_DeviceGroup implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DeviceGroup_DeviceGroup_DeviceGroup) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the DeviceGroup_DeviceGroup_DeviceGroup struct, which is a YANG list entry.
func (t *DeviceGroup_DeviceGroup_DeviceGroup) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}

	return map[string]interface{}{
		"id": *t.Id,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *DeviceGroup_DeviceGroup_DeviceGroup) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["DeviceGroup_DeviceGroup_DeviceGroup"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *DeviceGroup_DeviceGroup_DeviceGroup) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// DeviceRange_DeviceRange represents the /device-range/device-range YANG schema element.
type DeviceRange_DeviceRange struct {
	DeviceRange	map[string]*DeviceRange_DeviceRange_DeviceRange	`path:"device-range" module:"device-range"`
}

// IsYANGGoStruct ensures that DeviceRange_DeviceRange implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DeviceRange_DeviceRange) IsYANGGoStruct() {}

// NewDeviceRange creates a new entry in the DeviceRange list of the
// DeviceRange_DeviceRange struct. The keys of the list are populated from the input
// arguments.
func (t *DeviceRange_DeviceRange) NewDeviceRange(Id string) (*DeviceRange_DeviceRange_DeviceRange, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.DeviceRange == nil {
		t.DeviceRange = make(map[string]*DeviceRange_DeviceRange_DeviceRange)
	}

	key := Id

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.DeviceRange[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list DeviceRange", key)
	}

	t.DeviceRange[key] = &DeviceRange_DeviceRange_DeviceRange{
		Id: &Id,
	}

	return t.DeviceRange[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *DeviceRange_DeviceRange) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["DeviceRange_DeviceRange"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *DeviceRange_DeviceRange) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// DeviceRange_DeviceRange_DeviceRange represents the /device-range/device-range/device-range YANG schema element.
type DeviceRange_DeviceRange_DeviceRange struct {
	DeviceGroup	map[string]*DeviceRange_DeviceRange_DeviceRange_DeviceGroup	`path:"device-group" module:"device-range"`
	DisplayName	*string	`path:"display-name" module:"device-range"`
	Enabled	*bool	`path:"enabled" module:"device-range"`
	Enterprise	*string	`path:"enterprise" module:"device-range"`
	Id	*string	`path:"id" module:"device-range"`
	ImsiRangeFrom	*uint64	`path:"imsi-range-from" module:"device-range"`
	ImsiRangeTo	*uint64	`path:"imsi-range-to" module:"device-range"`
	ImsiWildcard	*string	`path:"imsi-wildcard" module:"device-range"`
	Priority	*uint32	`path:"priority" module:"device-range"`
}

// IsYANGGoStruct ensures that DeviceRange_DeviceRange_DeviceRange implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DeviceRange_DeviceRange_DeviceRange) IsYANGGoStruct() {}

// NewDeviceGroup creates a new entry in the DeviceGroup list of the
// DeviceRange_DeviceRange_DeviceRange struct. The keys of the list are populated from the input
// arguments.
func (t *DeviceRange_DeviceRange_DeviceRange) NewDeviceGroup(DeviceGroup string) (*DeviceRange_DeviceRange_DeviceRange_DeviceGroup, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.DeviceGroup == nil {
		t.DeviceGroup = make(map[string]*DeviceRange_DeviceRange_DeviceRange_DeviceGroup)
	}

	key := DeviceGroup

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.DeviceGroup[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list DeviceGroup", key)
	}

	t.DeviceGroup[key] = &DeviceRange_DeviceRange_DeviceRange_DeviceGroup{
		DeviceGroup: &DeviceGroup,
	}

	return t.DeviceGroup[key], nil
}

// ΛListKeyMap returns the keys of the DeviceRange_DeviceRange_DeviceRange struct, which is a YANG list entry.
func (t *DeviceRange_DeviceRange_DeviceRange) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}

	return map[string]interface{}{
		"id": *t.Id,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *DeviceRange_DeviceRange_DeviceRange) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["DeviceRange_DeviceRange_DeviceRange"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *DeviceRange_DeviceRange_DeviceRange) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// DeviceRange_DeviceRange_DeviceRange_DeviceGroup represents the /device-range/device-range/device-range/device-group YANG schema element.
type DeviceRange_DeviceRange_DeviceRange_DeviceGroup struct {
	Allowed	*bool	`path:"allowed" module:"device-range"`
	DeviceGroup	*string	`path:"device-group" module:"device-range"`
}

// IsYANGGoStruct ensures that DeviceRange_DeviceRange_DeviceRange_DeviceGroup implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*DeviceRange_DeviceRange_DeviceRange_DeviceGroup) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the DeviceRange_DeviceRange_DeviceRange_DeviceGroup struct, which is a YANG list entry.
func (t *DeviceRange_DeviceRange_DeviceRange_DeviceGroup) ΛListKeyMap() (map[string]interface{}, error) {
	if t.DeviceGroup == nil {
		return nil, fmt.Errorf("nil value for key DeviceGroup")
	}

	return map[string]interface{}{
		"device-group": *t.DeviceGroup,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *DeviceRange_DeviceRange_DeviceRange_DeviceGroup) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["DeviceRange_DeviceRange_DeviceRange_DeviceGroup"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *DeviceRange_DeviceRange_DeviceRange_DeviceGroup) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Enterprise_Enterprise represents the /enterprise/enterprise YANG schema element.
type Enterprise_Enterprise struct {
	Enterprise	map[string]*Enterprise_Enterprise_Enterprise	`path:"enterprise" module:"enterprise"`
}

// IsYANGGoStruct ensures that Enterprise_Enterprise implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Enterprise_Enterprise) IsYANGGoStruct() {}

// NewEnterprise creates a new entry in the Enterprise list of the
// Enterprise_Enterprise struct. The keys of the list are populated from the input
// arguments.
func (t *Enterprise_Enterprise) NewEnterprise(Id string) (*Enterprise_Enterprise_Enterprise, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Enterprise == nil {
		t.Enterprise = make(map[string]*Enterprise_Enterprise_Enterprise)
	}

	key := Id

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Enterprise[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Enterprise", key)
	}

	t.Enterprise[key] = &Enterprise_Enterprise_Enterprise{
		Id: &Id,
	}

	return t.Enterprise[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Enterprise_Enterprise) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Enterprise_Enterprise"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Enterprise_Enterprise) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Enterprise_Enterprise_Enterprise represents the /enterprise/enterprise/enterprise YANG schema element.
type Enterprise_Enterprise_Enterprise struct {
	Description	*string	`path:"description" module:"enterprise"`
	DisplayName	*string	`path:"display-name" module:"enterprise"`
	Id	*string	`path:"id" module:"enterprise"`
}

// IsYANGGoStruct ensures that Enterprise_Enterprise_Enterprise implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Enterprise_Enterprise_Enterprise) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Enterprise_Enterprise_Enterprise struct, which is a YANG list entry.
func (t *Enterprise_Enterprise_Enterprise) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}

	return map[string]interface{}{
		"id": *t.Id,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Enterprise_Enterprise_Enterprise) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Enterprise_Enterprise_Enterprise"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Enterprise_Enterprise_Enterprise) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Qos_Qos represents the /qos/qos YANG schema element.
type Qos_Qos struct {
	Qos	map[string]*Qos_Qos_Qos	`path:"qos" module:"qos"`
}

// IsYANGGoStruct ensures that Qos_Qos implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Qos_Qos) IsYANGGoStruct() {}

// NewQos creates a new entry in the Qos list of the
// Qos_Qos struct. The keys of the list are populated from the input
// arguments.
func (t *Qos_Qos) NewQos(Id string) (*Qos_Qos_Qos, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Qos == nil {
		t.Qos = make(map[string]*Qos_Qos_Qos)
	}

	key := Id

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Qos[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Qos", key)
	}

	t.Qos[key] = &Qos_Qos_Qos{
		Id: &Id,
	}

	return t.Qos[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Qos_Qos) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Qos_Qos"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Qos_Qos) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Qos_Qos_Qos represents the /qos/qos/qos YANG schema element.
type Qos_Qos_Qos struct {
	ConnectivityService	*Qos_Qos_Qos_ConnectivityService	`path:"connectivity-service" module:"qos"`
	Description	*string	`path:"description" module:"qos"`
	DisplayName	*string	`path:"display-name" module:"qos"`
	Id	*string	`path:"id" module:"qos"`
}

// IsYANGGoStruct ensures that Qos_Qos_Qos implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Qos_Qos_Qos) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Qos_Qos_Qos struct, which is a YANG list entry.
func (t *Qos_Qos_Qos) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}

	return map[string]interface{}{
		"id": *t.Id,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Qos_Qos_Qos) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Qos_Qos_Qos"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Qos_Qos_Qos) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Qos_Qos_Qos_ConnectivityService represents the /qos/qos/qos/connectivity-service YANG schema element.
type Qos_Qos_Qos_ConnectivityService struct {
	ApnAmbr	*Qos_Qos_Qos_ConnectivityService_ApnAmbr	`path:"apn-ambr" module:"qos"`
}

// IsYANGGoStruct ensures that Qos_Qos_Qos_ConnectivityService implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Qos_Qos_Qos_ConnectivityService) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Qos_Qos_Qos_ConnectivityService) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Qos_Qos_Qos_ConnectivityService"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Qos_Qos_Qos_ConnectivityService) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Qos_Qos_Qos_ConnectivityService_ApnAmbr represents the /qos/qos/qos/connectivity-service/apn-ambr YANG schema element.
type Qos_Qos_Qos_ConnectivityService_ApnAmbr struct {
	Downlink	*uint32	`path:"downlink" module:"qos"`
	Uplink	*uint32	`path:"uplink" module:"qos"`
}

// IsYANGGoStruct ensures that Qos_Qos_Qos_ConnectivityService_ApnAmbr implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Qos_Qos_Qos_ConnectivityService_ApnAmbr) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Qos_Qos_Qos_ConnectivityService_ApnAmbr) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Qos_Qos_Qos_ConnectivityService_ApnAmbr"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Qos_Qos_Qos_ConnectivityService_ApnAmbr) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Site_Site represents the /site/site YANG schema element.
type Site_Site struct {
	Site	map[string]*Site_Site_Site	`path:"site" module:"site"`
}

// IsYANGGoStruct ensures that Site_Site implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Site_Site) IsYANGGoStruct() {}

// NewSite creates a new entry in the Site list of the
// Site_Site struct. The keys of the list are populated from the input
// arguments.
func (t *Site_Site) NewSite(Id string) (*Site_Site_Site, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Site == nil {
		t.Site = make(map[string]*Site_Site_Site)
	}

	key := Id

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Site[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Site", key)
	}

	t.Site[key] = &Site_Site_Site{
		Id: &Id,
	}

	return t.Site[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Site_Site) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Site_Site"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Site_Site) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Site_Site_Site represents the /site/site/site YANG schema element.
type Site_Site_Site struct {
	Description	*string	`path:"description" module:"site"`
	DisplayName	*string	`path:"display-name" module:"site"`
	Enterprise	*string	`path:"enterprise" module:"site"`
	Id	*string	`path:"id" module:"site"`
}

// IsYANGGoStruct ensures that Site_Site_Site implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Site_Site_Site) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Site_Site_Site struct, which is a YANG list entry.
func (t *Site_Site_Site) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}

	return map[string]interface{}{
		"id": *t.Id,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Site_Site_Site) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Site_Site_Site"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Site_Site_Site) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// UseCase_UseCase represents the /use-case/use-case YANG schema element.
type UseCase_UseCase struct {
	UseCase	map[string]*UseCase_UseCase_UseCase	`path:"use-case" module:"use-case"`
}

// IsYANGGoStruct ensures that UseCase_UseCase implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UseCase_UseCase) IsYANGGoStruct() {}

// NewUseCase creates a new entry in the UseCase list of the
// UseCase_UseCase struct. The keys of the list are populated from the input
// arguments.
func (t *UseCase_UseCase) NewUseCase(Id string) (*UseCase_UseCase_UseCase, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.UseCase == nil {
		t.UseCase = make(map[string]*UseCase_UseCase_UseCase)
	}

	key := Id

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.UseCase[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list UseCase", key)
	}

	t.UseCase[key] = &UseCase_UseCase_UseCase{
		Id: &Id,
	}

	return t.UseCase[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UseCase_UseCase) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UseCase_UseCase"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UseCase_UseCase) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// UseCase_UseCase_UseCase represents the /use-case/use-case/use-case YANG schema element.
type UseCase_UseCase_UseCase struct {
	Application	map[string]*UseCase_UseCase_UseCase_Application	`path:"application" module:"use-case"`
	Description	*string	`path:"description" module:"use-case"`
	DeviceGroup	map[string]*UseCase_UseCase_UseCase_DeviceGroup	`path:"device-group" module:"use-case"`
	DisplayName	*string	`path:"display-name" module:"use-case"`
	Enterprise	*string	`path:"enterprise" module:"use-case"`
	Id	*string	`path:"id" module:"use-case"`
	Qos	map[string]*UseCase_UseCase_UseCase_Qos	`path:"qos" module:"use-case"`
	Site	map[string]*UseCase_UseCase_UseCase_Site	`path:"site" module:"use-case"`
	Visibility	map[string]*UseCase_UseCase_UseCase_Visibility	`path:"visibility" module:"use-case"`
}

// IsYANGGoStruct ensures that UseCase_UseCase_UseCase implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UseCase_UseCase_UseCase) IsYANGGoStruct() {}

// NewApplication creates a new entry in the Application list of the
// UseCase_UseCase_UseCase struct. The keys of the list are populated from the input
// arguments.
func (t *UseCase_UseCase_UseCase) NewApplication(Application string) (*UseCase_UseCase_UseCase_Application, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Application == nil {
		t.Application = make(map[string]*UseCase_UseCase_UseCase_Application)
	}

	key := Application

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Application[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Application", key)
	}

	t.Application[key] = &UseCase_UseCase_UseCase_Application{
		Application: &Application,
	}

	return t.Application[key], nil
}

// NewDeviceGroup creates a new entry in the DeviceGroup list of the
// UseCase_UseCase_UseCase struct. The keys of the list are populated from the input
// arguments.
func (t *UseCase_UseCase_UseCase) NewDeviceGroup(DeviceGroup string) (*UseCase_UseCase_UseCase_DeviceGroup, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.DeviceGroup == nil {
		t.DeviceGroup = make(map[string]*UseCase_UseCase_UseCase_DeviceGroup)
	}

	key := DeviceGroup

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.DeviceGroup[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list DeviceGroup", key)
	}

	t.DeviceGroup[key] = &UseCase_UseCase_UseCase_DeviceGroup{
		DeviceGroup: &DeviceGroup,
	}

	return t.DeviceGroup[key], nil
}

// NewQos creates a new entry in the Qos list of the
// UseCase_UseCase_UseCase struct. The keys of the list are populated from the input
// arguments.
func (t *UseCase_UseCase_UseCase) NewQos(Qos string) (*UseCase_UseCase_UseCase_Qos, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Qos == nil {
		t.Qos = make(map[string]*UseCase_UseCase_UseCase_Qos)
	}

	key := Qos

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Qos[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Qos", key)
	}

	t.Qos[key] = &UseCase_UseCase_UseCase_Qos{
		Qos: &Qos,
	}

	return t.Qos[key], nil
}

// NewSite creates a new entry in the Site list of the
// UseCase_UseCase_UseCase struct. The keys of the list are populated from the input
// arguments.
func (t *UseCase_UseCase_UseCase) NewSite(Site string) (*UseCase_UseCase_UseCase_Site, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Site == nil {
		t.Site = make(map[string]*UseCase_UseCase_UseCase_Site)
	}

	key := Site

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Site[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Site", key)
	}

	t.Site[key] = &UseCase_UseCase_UseCase_Site{
		Site: &Site,
	}

	return t.Site[key], nil
}

// NewVisibility creates a new entry in the Visibility list of the
// UseCase_UseCase_UseCase struct. The keys of the list are populated from the input
// arguments.
func (t *UseCase_UseCase_UseCase) NewVisibility(Visibility string) (*UseCase_UseCase_UseCase_Visibility, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Visibility == nil {
		t.Visibility = make(map[string]*UseCase_UseCase_UseCase_Visibility)
	}

	key := Visibility

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Visibility[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Visibility", key)
	}

	t.Visibility[key] = &UseCase_UseCase_UseCase_Visibility{
		Visibility: &Visibility,
	}

	return t.Visibility[key], nil
}

// ΛListKeyMap returns the keys of the UseCase_UseCase_UseCase struct, which is a YANG list entry.
func (t *UseCase_UseCase_UseCase) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}

	return map[string]interface{}{
		"id": *t.Id,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UseCase_UseCase_UseCase) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UseCase_UseCase_UseCase"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UseCase_UseCase_UseCase) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// UseCase_UseCase_UseCase_Application represents the /use-case/use-case/use-case/application YANG schema element.
type UseCase_UseCase_UseCase_Application struct {
	Allowed	*bool	`path:"allowed" module:"use-case"`
	Application	*string	`path:"application" module:"use-case"`
}

// IsYANGGoStruct ensures that UseCase_UseCase_UseCase_Application implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UseCase_UseCase_UseCase_Application) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the UseCase_UseCase_UseCase_Application struct, which is a YANG list entry.
func (t *UseCase_UseCase_UseCase_Application) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Application == nil {
		return nil, fmt.Errorf("nil value for key Application")
	}

	return map[string]interface{}{
		"application": *t.Application,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UseCase_UseCase_UseCase_Application) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UseCase_UseCase_UseCase_Application"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UseCase_UseCase_UseCase_Application) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// UseCase_UseCase_UseCase_DeviceGroup represents the /use-case/use-case/use-case/device-group YANG schema element.
type UseCase_UseCase_UseCase_DeviceGroup struct {
	Allowed	*bool	`path:"allowed" module:"use-case"`
	DeviceGroup	*string	`path:"device-group" module:"use-case"`
}

// IsYANGGoStruct ensures that UseCase_UseCase_UseCase_DeviceGroup implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UseCase_UseCase_UseCase_DeviceGroup) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the UseCase_UseCase_UseCase_DeviceGroup struct, which is a YANG list entry.
func (t *UseCase_UseCase_UseCase_DeviceGroup) ΛListKeyMap() (map[string]interface{}, error) {
	if t.DeviceGroup == nil {
		return nil, fmt.Errorf("nil value for key DeviceGroup")
	}

	return map[string]interface{}{
		"device-group": *t.DeviceGroup,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UseCase_UseCase_UseCase_DeviceGroup) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UseCase_UseCase_UseCase_DeviceGroup"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UseCase_UseCase_UseCase_DeviceGroup) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// UseCase_UseCase_UseCase_Qos represents the /use-case/use-case/use-case/qos YANG schema element.
type UseCase_UseCase_UseCase_Qos struct {
	Allowed	*bool	`path:"allowed" module:"use-case"`
	Qos	*string	`path:"qos" module:"use-case"`
}

// IsYANGGoStruct ensures that UseCase_UseCase_UseCase_Qos implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UseCase_UseCase_UseCase_Qos) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the UseCase_UseCase_UseCase_Qos struct, which is a YANG list entry.
func (t *UseCase_UseCase_UseCase_Qos) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Qos == nil {
		return nil, fmt.Errorf("nil value for key Qos")
	}

	return map[string]interface{}{
		"qos": *t.Qos,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UseCase_UseCase_UseCase_Qos) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UseCase_UseCase_UseCase_Qos"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UseCase_UseCase_UseCase_Qos) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// UseCase_UseCase_UseCase_Site represents the /use-case/use-case/use-case/site YANG schema element.
type UseCase_UseCase_UseCase_Site struct {
	Allowed	*bool	`path:"allowed" module:"use-case"`
	Site	*string	`path:"site" module:"use-case"`
}

// IsYANGGoStruct ensures that UseCase_UseCase_UseCase_Site implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UseCase_UseCase_UseCase_Site) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the UseCase_UseCase_UseCase_Site struct, which is a YANG list entry.
func (t *UseCase_UseCase_UseCase_Site) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Site == nil {
		return nil, fmt.Errorf("nil value for key Site")
	}

	return map[string]interface{}{
		"site": *t.Site,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UseCase_UseCase_UseCase_Site) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UseCase_UseCase_UseCase_Site"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UseCase_UseCase_UseCase_Site) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// UseCase_UseCase_UseCase_Visibility represents the /use-case/use-case/use-case/visibility YANG schema element.
type UseCase_UseCase_UseCase_Visibility struct {
	Allowed	*bool	`path:"allowed" module:"use-case"`
	Visibility	*string	`path:"visibility" module:"use-case"`
}

// IsYANGGoStruct ensures that UseCase_UseCase_UseCase_Visibility implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*UseCase_UseCase_UseCase_Visibility) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the UseCase_UseCase_UseCase_Visibility struct, which is a YANG list entry.
func (t *UseCase_UseCase_UseCase_Visibility) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Visibility == nil {
		return nil, fmt.Errorf("nil value for key Visibility")
	}

	return map[string]interface{}{
		"visibility": *t.Visibility,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *UseCase_UseCase_UseCase_Visibility) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["UseCase_UseCase_UseCase_Visibility"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *UseCase_UseCase_UseCase_Visibility) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Visibility_Visibility represents the /visibility/visibility YANG schema element.
type Visibility_Visibility struct {
	Visibility	map[string]*Visibility_Visibility_Visibility	`path:"visibility" module:"visibility"`
}

// IsYANGGoStruct ensures that Visibility_Visibility implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Visibility_Visibility) IsYANGGoStruct() {}

// NewVisibility creates a new entry in the Visibility list of the
// Visibility_Visibility struct. The keys of the list are populated from the input
// arguments.
func (t *Visibility_Visibility) NewVisibility(Id string) (*Visibility_Visibility_Visibility, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Visibility == nil {
		t.Visibility = make(map[string]*Visibility_Visibility_Visibility)
	}

	key := Id

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Visibility[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Visibility", key)
	}

	t.Visibility[key] = &Visibility_Visibility_Visibility{
		Id: &Id,
	}

	return t.Visibility[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Visibility_Visibility) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Visibility_Visibility"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Visibility_Visibility) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Visibility_Visibility_Visibility represents the /visibility/visibility/visibility YANG schema element.
type Visibility_Visibility_Visibility struct {
	Application	*string	`path:"application" module:"visibility"`
	Description	*string	`path:"description" module:"visibility"`
	DisplayName	*string	`path:"display-name" module:"visibility"`
	Id	*string	`path:"id" module:"visibility"`
}

// IsYANGGoStruct ensures that Visibility_Visibility_Visibility implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Visibility_Visibility_Visibility) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Visibility_Visibility_Visibility struct, which is a YANG list entry.
func (t *Visibility_Visibility_Visibility) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Id == nil {
		return nil, fmt.Errorf("nil value for key Id")
	}

	return map[string]interface{}{
		"id": *t.Id,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Visibility_Visibility_Visibility) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Visibility_Visibility_Visibility"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Visibility_Visibility_Visibility) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }



var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5d, 0x5d, 0x73, 0xe2, 0x46,
		0xd6, 0xbe, 0xf7, 0xaf, 0xa0, 0xa8, 0x4a, 0x95, 0x99, 0x18, 0x07, 0x6c, 0x6c, 0x8f, 0xb9, 0x71,
		0xf9, 0xcd, 0x4c, 0xf2, 0x56, 0x65, 0x26, 0x9b, 0xc9, 0xec, 0xe6, 0x62, 0x6d, 0x96, 0x92, 0xa1,
		0xcd, 0x74, 0x05, 0x4b, 0xb2, 0x24, 0x3c, 0xe3, 0xf5, 0xf0, 0xdf, 0xb7, 0x84, 0x40, 0x08, 0xa3,
		0x8f, 0x73, 0x5a, 0xa2, 0x91, 0xe0, 0xb9, 0xb0, 0x91, 0x40, 0x2d, 0x75, 0x9f, 0x3e, 0xe7, 0xe9,
		0xd3, 0xe7, 0x4b, 0x2f, 0x07, 0xb5, 0x5a, 0xad, 0x56, 0xff, 0xdd, 0x78, 0x10, 0xf5, 0x6e, 0xad,
		0x3e, 0x14, 0x4f, 0x72, 0x20, 0xea, 0x47, 0xc1, 0xb7, 0xbf, 0x49, 0x73, 0x58, 0xef, 0xd6, 0xda,
		0xf3, 0xd3, 0x9f, 0x2d, 0xf3, 0x5e, 0x8e, 0xea, 0xdd, 0x5a, 0x6b, 0xfe, 0xc5, 0x3b, 0xe9, 0xd4,
		0xbb, 0xb5, 0xe0, 0x16, 0xb3, 0x2f, 0x0c, 0xdb, 0x1e, 0xcb, 0x81, 0xe1, 0x49, 0xcb, 0x5c, 0xf9,
		0x61, 0xe5, 0x19, 0xd1, 0x8b, 0x8e, 0x56, 0x2f, 0x59, 0x7d, 0x60, 0xf8, 0xf5, 0xeb, 0x07, 0x87,
		0x3f, 0xfc, 0xe1, 0x88, 0x7b, 0xf9, 0x6d, 0xed, 0x51, 0xaf, 0x1f, 0xf7, 0xea, 0x31, 0xb3, 0x9f,
		0x3f, 0x5b, 0x13, 0x67, 0x20, 0x62, 0x9b, 0x06, 0x5d, 0x11, 0xcf, 0x5f, 0x2d, 0xc7, 0xef, 0x4d,
		0xdd, 0x0e, 0x9e, 0x72, 0x14, 0x7f, 0xe1, 0xff, 0x1b, 0xee, 0xb5, 0x33, 0x9a, 0x3c, 0x08, 0xd3,
		0xab, 0x77, 0x6b, 0x9e, 0x33, 0x11, 0x09, 0x17, 0x46, 0xae, 0x9a, 0x75, 0x6a, 0xed, 0xaa, 0xe9,
		0xca, 0x37, 0xd3, 0x57, 0x63, 0x7d, 0x4d, 0x6c, 0x12, 0xd1, 0x19, 0xc4, 0xcf, 0x98, 0x84, 0xcc,
		0xc9, 0xa0, 0x4c, 0x0a, 0x71, 0x72, 0xa8, 0x93, 0xc4, 0x9e, 0x2c, 0xf6, 0xa4, 0xd1, 0x27, 0x2f,
		0x7e, 0x12, 0x13, 0x26, 0x33, 0x73, 0x52, 0xc3, 0x0b, 0x86, 0xc2, 0x1e, 0x5b, 0xcf, 0xfe, 0x93,
		0x9b, 0xc2, 0x7c, 0x92, 0x8e, 0x65, 0xce, 0x7b, 0x91, 0x41, 0x91, 0xa5, 0x40, 0xc7, 0xb6, 0xcf,
		0x18, 0xed, 0x9c, 0x05, 0x5a, 0x19, 0x97, 0x65, 0xb1, 0x02, 0x87, 0x25, 0x98, 0xac, 0xc1, 0x65,
		0x11, 0x65, 0x56, 0x51, 0x66, 0x19, 0x3e, 0xeb, 0xa4, 0xb3, 0x50, 0x06, 0x2b, 0x85, 0x8f, 0xfb,
		0xe7, 0xb3, 0x2d, 0x78, 0x94, 0x1e, 0x0b, 0xe3, 0xde, 0x11, 0xf7, 0x14, 0x6a, 0x2f, 0xb0, 0xe1,
		0x82, 0x70, 0xed, 0x1f, 0x86, 0xf7, 0xc5, 0xbf, 0xfd, 0x4f, 0x43, 0xd1, 0x8d, 0x67, 0xc3, 0xf4,
		0x5f, 0xe4, 0x30, 0x9d, 0x54, 0xc9, 0x64, 0x4a, 0x21, 0x51, 0x7d, 0x28, 0xdc, 0x81, 0x23, 0xed,
		0x54, 0xb4, 0x8c, 0x91, 0xa2, 0x65, 0x23, 0x88, 0x0e, 0x44, 0x27, 0xa4, 0xb4, 0xeb, 0x39, 0xd2,
		0x1c, 0x71, 0x24, 0xe7, 0x2d, 0xe1, 0xda, 0x0f, 0xc2, 0x1c, 0xcd, 0x64, 0xe7, 0x86, 0x44, 0x26,
		0xda, 0xf4, 0xcd, 0xee, 0xfc, 0x51, 0x9a, 0xe4, 0xf9, 0x66, 0xb2, 0xf4, 0x5a, 0xb3, 0xbf, 0x8c,
		0xf1, 0x44, 0x24, 0x2b, 0x12, 0x89, 0xed, 0x7e, 0x71, 0x8c, 0x81, 0x2f, 0x69, 0xef, 0xe4, 0x48,
		0x7a, 0xae, 0xff, 0x60, 0x72, 0xfb, 0xe9, 0x11, 0x83, 0x14, 0xc6, 0x37, 0xfd, 0xa4, 0x68, 0xb5,
		0x34, 0x12, 0xe3, 0xa0, 0x98, 0xab, 0x7a, 0x9b, 0x40, 0x61, 0xe9, 0xda, 0x63, 0xe3, 0xb9, 0x69,
		0x06, 0x72, 0x44, 0x85, 0xe1, 0x68, 0x2b, 0xe0, 0x30, 0x70, 0x18, 0x38, 0x0c, 0x1c, 0x56, 0x21,
		0xc5, 0x5b, 0xc0, 0xf0, 0x6c, 0x58, 0xc2, 0x1c, 0xda, 0x96, 0xe4, 0xec, 0x27, 0xc3, 0x16, 0x34,
		0xf8, 0x6d, 0x03, 0x7e, 0xab, 0x07, 0xbf, 0x59, 0x46, 0x89, 0xf0, 0xc2, 0x2f, 0x96, 0xeb, 0x91,
		0x56, 0xf0, 0xb5, 0xa9, 0x09, 0x5b, 0x12, 0x29, 0xc0, 0x93, 0x77, 0x32, 0x5b, 0xa9, 0xb0, 0x97,
		0x22, 0x9b, 0xa9, 0xb2, 0x5b, 0x6e, 0xb6, 0xcb, 0xcd, 0x7e, 0xea, 0x6c, 0xc8, 0x84, 0x40, 0xe2,
		0x5c, 0x91, 0xb5, 0x83, 0x58, 0xae, 0xe3, 0x4c, 0xd5, 0x02, 0xc4, 0x2e, 0x19, 0x6d, 0xe6, 0xbd,
		0xbb, 0x61, 0x91, 0x96, 0xc7, 0x0a, 0x2b, 0x63, 0x92, 0x76, 0xd3, 0x18, 0x0e, 0x1d, 0xe1, 0xba,
		0x4c, 0x7e, 0x50, 0x1d, 0x61, 0xbe, 0x91, 0xaa, 0x8f, 0x38, 0x66, 0xe4, 0x4f, 0x9d, 0x1c, 0x63,
		0x57, 0xd1, 0x08, 0xd3, 0x6c, 0x5d, 0x9e, 0x70, 0x4c, 0x65, 0x72, 0x84, 0x37, 0x3a, 0x3c, 0xbc,
		0x69, 0x35, 0x2f, 0x7b, 0xdf, 0x6f, 0xda, 0xcd, 0xcb, 0x5e, 0x70, 0xd8, 0x9e, 0x7d, 0x04, 0xc7,
		0x27, 0x37, 0xad, 0x66, 0x67, 0x71, 0x7c, 0x76, 0xd3, 0x6a, 0x9e, 0xf5, 0x1a, 0xb7, 0xb7, 0xc7,
		0x8d, 0x97, 0xd3, 0x29, 0xbf, 0xe1, 0xe1, 0x0f, 0x37, 0xb7, 0xb7, 0xf6, 0xcb, 0xef, 0x53, 0xff,
		0xff, 0x87, 0x69, 0xef, 0xc7, 0xc6, 0x55, 0x5d, 0xb9, 0xf7, 0x3d, 0xa5, 0x96, 0xd3, 0xa3, 0x2d,
		0x72, 0xcf, 0xf9, 0x0e, 0x72, 0x4f, 0xf7, 0xbb, 0x3f, 0xc7, 0x46, 0xf3, 0xfe, 0xba, 0xf9, 0x4b,
		0xef, 0xa5, 0x75, 0xd4, 0x99, 0x36, 0xba, 0x8d, 0xc3, 0xd7, 0xdf, 0x75, 0x1b, 0x2f, 0xad, 0xa3,
		0xb3, 0xe9, 0xe1, 0x61, 0xcc, 0x2f, 0x57, 0x71, 0xf7, 0x68, 0x7c, 0x3f, 0x3c, 0x3c, 0x9c, 0xf3,
		0xcd, 0x0a, 0x2f, 0xdd, 0xb4, 0xda, 0xbd, 0xab, 0xd9, 0x61, 0xf0, 0x3f, 0xe4, 0x46, 0xd2, 0xc5,
		0x8d, 0x58, 0x1e, 0x3c, 0xca, 0x2d, 0x42, 0xff, 0xe9, 0xf6, 0x7e, 0xec, 0x36, 0x5e, 0xce, 0xa7,
		0x8b, 0xe3, 0xd9, 0xff, 0xc6, 0xf7, 0xc3, 0xe3, 0x37, 0xb7, 0xb7, 0xc7, 0xc7, 0x6f, 0x1a, 0xc1,
		0x80, 0xe6, 0xd7, 0xbd, 0x09, 0x7e, 0xbd, 0xea, 0x76, 0xd7, 0xbe, 0x6a, 0x1c, 0xfe, 0x70, 0xbc,
		0x0d, 0xb1, 0x38, 0xd8, 0xec, 0x73, 0x98, 0x62, 0x97, 0x63, 0x79, 0x1a, 0x5a, 0x0f, 0x86, 0x34,
		0x9b, 0x0c, 0x5d, 0xaf, 0x28, 0xe9, 0xe2, 0xee, 0xde, 0x0b, 0xc4, 0x18, 0x95, 0xdd, 0x7d, 0x41,
		0x5b, 0xdc, 0xa2, 0x76, 0xff, 0x45, 0xee, 0x80, 0x0b, 0x02, 0x7d, 0x65, 0x6b, 0xc1, 0xa6, 0x49,
		0x7b, 0x72, 0x76, 0x5a, 0x22, 0xe2, 0xea, 0x02, 0x1c, 0x05, 0x89, 0xcc, 0xbb, 0xce, 0xd5, 0x7d,
		0xcc, 0x36, 0x9a, 0xff, 0xbd, 0x6e, 0xfe, 0xbb, 0xd5, 0xbc, 0xec, 0xf7, 0x22, 0x27, 0xb7, 0xb7,
		0xcd, 0x7e, 0xcf, 0x5f, 0xd5, 0xce, 0xdb, 0xd3, 0xc6, 0xd5, 0xf2, 0xfb, 0x9e, 0xbf, 0x1e, 0xbd,
		0x51, 0x69, 0x75, 0xd5, 0xf8, 0x7e, 0x7b, 0x7b, 0x5c, 0xdf, 0x34, 0x12, 0x1f, 0x14, 0x7b, 0xdf,
		0xec, 0xfb, 0x11, 0xa4, 0xaf, 0xae, 0xb6, 0xa9, 0xc7, 0x86, 0x1e, 0x1b, 0x7a, 0xbd, 0x1b, 0x7a,
		0xb2, 0xd9, 0x7f, 0x5d, 0xa1, 0xd0, 0x28, 0x4d, 0xb6, 0xe5, 0x78, 0x7c, 0x69, 0x9a, 0xb5, 0x82,
		0x34, 0x41, 0x9a, 0xb4, 0x49, 0x93, 0xcf, 0x71, 0x4d, 0x73, 0xf2, 0x70, 0x27, 0x1c, 0x05, 0x91,
		0x3a, 0x67, 0x34, 0xf9, 0xd3, 0x30, 0x47, 0x5a, 0xac, 0x64, 0x79, 0x34, 0xf1, 0x9c, 0x6a, 0x62,
		0xa8, 0x1e, 0xaa, 0xb6, 0x2f, 0x40, 0x29, 0x54, 0xd0, 0xb4, 0x73, 0x69, 0xd8, 0x45, 0x91, 0xec,
		0xfc, 0xec, 0xec, 0xf4, 0x6c, 0x8b, 0x64, 0x2b, 0xbb, 0x0a, 0x97, 0xcb, 0xbd, 0xf3, 0x9b, 0x78,
		0x26, 0x6a, 0x6b, 0xf5, 0x0f, 0xd2, 0xf5, 0xae, 0x3d, 0x8f, 0xe8, 0x0e, 0xfa, 0x28, 0xcd, 0xf7,
		0x63, 0xe1, 0x43, 0xa0, 0x4f, 0x76, 0x73, 0x32, 0x1e, 0x13, 0x16, 0xc7, 0x8f, 0xc6, 0x37, 0x7e,
		0xa3, 0x7f, 0x38, 0x43, 0xe1, 0x88, 0xe1, 0xff, 0x3d, 0xcf, 0x9b, 0xe4, 0xa2, 0xc7, 0xb5, 0x69,
		0x5a, 0x9e, 0x41, 0x0a, 0x08, 0x9c, 0x5d, 0xef, 0x0e, 0xbe, 0x88, 0x07, 0xc3, 0x5e, 0x44, 0x37,
		0x46, 0x22, 0xaa, 0x13, 0x8f, 0x89, 0x5e, 0xd3, 0xe0, 0xf6, 0x9e, 0x33, 0x19, 0x2c, 0xdc, 0x6a,
		0xf5, 0xeb, 0xe5, 0x5d, 0xfa, 0x49, 0xc7, 0xef, 0x17, 0x77, 0xdf, 0x80, 0x87, 0x58, 0x0e, 0xe9,
		0xbe, 0x61, 0x39, 0x44, 0x50, 0x0e, 0x82, 0x72, 0x62, 0x73, 0x0d, 0x9a, 0x99, 0xbc, 0x51, 0x43,
		0x70, 0x8e, 0xa6, 0x55, 0xae, 0xec, 0xc1, 0x39, 0xa7, 0x27, 0x08, 0xce, 0xf1, 0x87, 0xf5, 0x68,
		0xb9, 0x74, 0xec, 0xf5, 0x2f, 0x46, 0x48, 0x0e, 0x42, 0x72, 0x8c, 0xf1, 0xd8, 0xfa, 0x2a, 0x86,
		0x7c, 0x73, 0xc3, 0xa2, 0x21, 0x71, 0xfc, 0xef, 0xc4, 0xbd, 0x31, 0x19, 0xcf, 0x86, 0xef, 0x53,
		0x0d, 0x86, 0x0a, 0x18, 0x2a, 0xf4, 0x19, 0x2a, 0xee, 0x2c, 0x6b, 0x2c, 0x0c, 0x53, 0xc5, 0xee,
		0xd7, 0xd6, 0x68, 0xf7, 0xa3, 0x00, 0xb8, 0x02, 0x90, 0x43, 0x98, 0x20, 0x4c, 0x05, 0x0a, 0x13,
		0x3d, 0xfb, 0x6f, 0x4d, 0x98, 0x2e, 0x18, 0x6d, 0xc2, 0x6c, 0xc0, 0x47, 0xcb, 0xed, 0x3e, 0x5a,
		0xee, 0xca, 0x67, 0x56, 0xaa, 0x9f, 0x66, 0xd3, 0x08, 0x41, 0x99, 0x82, 0x65, 0xa4, 0x18, 0xcb,
		0x08, 0x0d, 0xee, 0x14, 0x8c, 0x22, 0x9f, 0x2c, 0x57, 0xd9, 0x1e, 0xc2, 0x4a, 0xe1, 0x9e, 0xf3,
		0x4c, 0xe2, 0x06, 0x97, 0xc6, 0x2a, 0x2c, 0x16, 0x61, 0xb1, 0x06, 0x8d, 0x25, 0x92, 0x46, 0x47,
		0x64, 0x01, 0x85, 0xa9, 0x4f, 0xcb, 0xfb, 0x67, 0x4f, 0x77, 0xfc, 0x54, 0x4f, 0x99, 0x25, 0x16,
		0x32, 0x06, 0x4b, 0x1c, 0x64, 0x5c, 0xb5, 0x09, 0xd2, 0x80, 0x56, 0x07, 0xb1, 0xec, 0x6a, 0xa4,
		0x9b, 0xd4, 0x7a, 0x00, 0xbc, 0xfc, 0xff, 0x8d, 0xd4, 0xdd, 0x20, 0x57, 0x1e, 0xd8, 0x72, 0x29,
		0x8e, 0x84, 0x7e, 0x16, 0x55, 0x9d, 0x83, 0x59, 0xc0, 0x41, 0xad, 0x70, 0x83, 0xd6, 0x9a, 0x1d,
		0xec, 0x92, 0x12, 0x25, 0x2d, 0xe3, 0x41, 0x9d, 0x78, 0xb5, 0x65, 0x21, 0xb3, 0xb2, 0xc7, 0x60,
		0x3c, 0x71, 0x3d, 0xe1, 0x30, 0x53, 0x60, 0x57, 0x5a, 0x55, 0xc0, 0xda, 0xae, 0x54, 0x7f, 0xa4,
		0x82, 0x36, 0x20, 0x2e, 0x33, 0x6d, 0xcb, 0x26, 0x8f, 0x44, 0x59, 0xd8, 0xe2, 0x19, 0xa4, 0x40,
		0xa2, 0xec, 0x62, 0x15, 0xdf, 0xfd, 0xaa, 0x31, 0x80, 0x6a, 0x40, 0x35, 0xa0, 0xba, 0xb2, 0x50,
		0x8d, 0xda, 0x32, 0x0b, 0xac, 0xde, 0x8b, 0xda, 0x32, 0x40, 0x6b, 0xa0, 0x35, 0xd0, 0x1a, 0x8a,
		0x75, 0xc5, 0xc1, 0x7a, 0xf7, 0xe2, 0x0b, 0x01, 0xcc, 0xe5, 0x02, 0xe6, 0xf8, 0x7e, 0x22, 0x20,
		0x11, 0x58, 0x4d, 0x25, 0x05, 0x02, 0x12, 0x83, 0x61, 0xb9, 0xd2, 0x63, 0x28, 0xd4, 0xb3, 0xab,
		0x81, 0xd7, 0xc0, 0xeb, 0x92, 0x55, 0xa3, 0x76, 0xbd, 0xae, 0xcf, 0x9a, 0xd1, 0xcf, 0x1c, 0x95,
		0xa6, 0x11, 0x2a, 0xb0, 0x64, 0x36, 0xb5, 0x50, 0x81, 0xc4, 0x02, 0xe0, 0x8c, 0xaf, 0xe9, 0xb1,
		0x04, 0xef, 0xc2, 0xf6, 0xef, 0x97, 0xcd, 0xfb, 0x8c, 0x6f, 0xb7, 0x12, 0x69, 0x90, 0x97, 0x18,
		0xea, 0x44, 0xa0, 0xc5, 0x24, 0x3c, 0xc9, 0x81, 0x68, 0x8e, 0x1c, 0x6b, 0x62, 0xa7, 0x45, 0x22,
		0x44, 0xae, 0xd2, 0x11, 0x7f, 0x30, 0x2a, 0x61, 0xac, 0xc1, 0xa8, 0xc0, 0xb8, 0x82, 0x14, 0xa2,
		0x73, 0x88, 0x9f, 0x31, 0x09, 0xe4, 0x45, 0x98, 0x17, 0x43, 0x30, 0xaa, 0x60, 0xbc, 0xc0, 0x48,
		0xe3, 0x5b, 0x3f, 0xf6, 0xc0, 0xdd, 0x34, 0xda, 0x41, 0x1d, 0x6b, 0x04, 0xc3, 0x24, 0x36, 0xbb,
		0x95, 0xde, 0xec, 0xc2, 0x8d, 0xb4, 0xc0, 0xe0, 0xfd, 0x70, 0x23, 0x01, 0x85, 0x81, 0xc2, 0x40,
		0xe1, 0xb2, 0xa1, 0x30, 0xdc, 0x43, 0xc1, 0xb0, 0x76, 0xd0, 0x3d, 0x04, 0xc0, 0xd5, 0x02, 0xb8,
		0xd1, 0x1d, 0x2f, 0x9c, 0x3d, 0x40, 0x5e, 0x2a, 0x29, 0xf6, 0xca, 0xd9, 0x03, 0xeb, 0x75, 0x7e,
		0xeb, 0xf5, 0x12, 0x66, 0x92, 0x4f, 0x38, 0xf6, 0x69, 0xbf, 0xd5, 0xaf, 0x7e, 0xa3, 0x7e, 0xc2,
		0xf1, 0x96, 0x2c, 0xd0, 0xf4, 0xa1, 0xd1, 0x86, 0xc4, 0xb0, 0x2c, 0x3b, 0xf3, 0x72, 0x81, 0xe9,
		0x96, 0xe5, 0xe0, 0x2a, 0x1d, 0x96, 0x65, 0xa7, 0x84, 0x96, 0x65, 0xa7, 0x68, 0xcb, 0x72, 0x3c,
		0xd1, 0x39, 0xc4, 0xdf, 0x8e, 0x65, 0xd9, 0xa9, 0xa0, 0x65, 0xd9, 0xd1, 0x68, 0x59, 0x26, 0xb8,
		0x0d, 0x54, 0xdc, 0x07, 0xc4, 0xc9, 0xd6, 0xa4, 0x64, 0x3b, 0x3b, 0xa8, 0x64, 0x3b, 0x28, 0x32,
		0x54, 0xfd, 0xba, 0x28, 0x43, 0x67, 0xff, 0xca, 0xa2, 0x50, 0x38, 0x97, 0xa9, 0x12, 0xa3, 0xc4,
		0x90, 0x02, 0x9c, 0xe7, 0x81, 0x75, 0x08, 0x17, 0x84, 0xab, 0x30, 0xe1, 0xd2, 0x5d, 0x72, 0x68,
		0x38, 0xea, 0xae, 0xee, 0x5f, 0xd6, 0xcf, 0x4b, 0x56, 0x81, 0x88, 0xa3, 0x70, 0xa1, 0x14, 0x11,
		0x79, 0x9b, 0x3e, 0xdb, 0xa5, 0x64, 0x9f, 0x50, 0x01, 0x31, 0x76, 0xa3, 0x3b, 0xab, 0x6d, 0xdf,
		0x4f, 0x3f, 0x4e, 0xd9, 0xc7, 0xe7, 0xb3, 0x97, 0xef, 0x89, 0xd3, 0x12, 0xea, 0xbd, 0x16, 0x1b,
		0x3a, 0x9c, 0x96, 0x30, 0x9d, 0x33, 0x48, 0x01, 0xa7, 0x65, 0x30, 0x2c, 0x61, 0x1a, 0x77, 0x63,
		0x31, 0xe4, 0xbc, 0x54, 0x3d, 0x68, 0x90, 0xb5, 0x3f, 0x5f, 0x6e, 0x87, 0xef, 0x8d, 0xb1, 0x0b,
		0xa8, 0x06, 0x54, 0x2b, 0xec, 0x57, 0x89, 0xfb, 0x54, 0x55, 0xd6, 0xf7, 0x84, 0x63, 0x3b, 0xd2,
		0x15, 0x1c, 0xee, 0x0f, 0xdb, 0x80, 0xa1, 0xc1, 0xd0, 0x9a, 0xd2, 0x80, 0x84, 0xe9, 0x75, 0x97,
		0x9c, 0x17, 0x77, 0x9a, 0x23, 0x2b, 0x68, 0xbf, 0x22, 0x5a, 0x20, 0x11, 0x5a, 0x24, 0x62, 0x32,
		0x29, 0x3e, 0x8c, 0x85, 0xfb, 0x46, 0xd6, 0x7a, 0xf4, 0xcd, 0xe0, 0x6f, 0xa7, 0xcd, 0xe8, 0x69,
		0x87, 0x73, 0xda, 0x3e, 0x99, 0xd6, 0xb7, 0x13, 0x51, 0xf6, 0xe0, 0x4a, 0x86, 0x04, 0xfa, 0x57,
		0xd3, 0x64, 0xf0, 0x0c, 0x32, 0x58, 0x35, 0x19, 0x24, 0x3b, 0xbc, 0xd2, 0x7d, 0xe1, 0x89, 0xb3,
		0x92, 0xe6, 0x14, 0x4f, 0x62, 0xa3, 0x0e, 0x0c, 0xeb, 0xfb, 0x6e, 0x58, 0xa7, 0xb2, 0xe5, 0x0a,
		0xa6, 0x05, 0x16, 0xcc, 0xe6, 0xbd, 0x63, 0x3d, 0xf0, 0x29, 0x1f, 0x85, 0xbb, 0xe8, 0x8d, 0x8e,
		0xb4, 0xd8, 0x0f, 0xb8, 0xac, 0x9c, 0x87, 0xa5, 0xf3, 0xb1, 0x76, 0x5e, 0x16, 0x2f, 0x8c, 0xd5,
		0x0b, 0x63, 0xf9, 0xdc, 0xac, 0xcf, 0x13, 0x01, 0x05, 0x53, 0x56, 0x4d, 0xc9, 0xd7, 0xb4, 0xae,
		0x3d, 0x49, 0xd3, 0x3b, 0xef, 0xa8, 0xcc, 0xf5, 0x9c, 0xab, 0xdf, 0x2a, 0x34, 0x55, 0x7b, 0xcf,
		0x2d, 0xdf, 0xf2, 0x59, 0x88, 0x25, 0xb4, 0x20, 0x71, 0x4e, 0x34, 0x0f, 0xe6, 0xbd, 0x4f, 0x01,
		0x2f, 0x76, 0x55, 0x64, 0xbf, 0xdc, 0x96, 0xd5, 0x4d, 0x93, 0xb6, 0xfd, 0xb6, 0xd3, 0x39, 0xbf,
		0xe8, 0x74, 0x5a, 0x17, 0xa7, 0x17, 0xad, 0xcb, 0xb3, 0xb3, 0xf6, 0x79, 0xfb, 0xac, 0x44, 0xd4,
		0x3e, 0xd0, 0xd3, 0xaa, 0xb7, 0xa1, 0xd7, 0xf6, 0x72, 0xec, 0xee, 0x91, 0x15, 0xd4, 0xb3, 0x0a,
		0x59, 0x88, 0x3d, 0x0b, 0xcb, 0x30, 0x96, 0x61, 0x2c, 0xc3, 0x58, 0x86, 0xb1, 0x0c, 0x63, 0x19,
		0xde, 0xe7, 0x65, 0xb8, 0xd0, 0x4d, 0x36, 0x33, 0xa0, 0x28, 0x6c, 0xa7, 0x16, 0x58, 0xe4, 0xaf,
		0xe7, 0x3f, 0x05, 0xe6, 0x20, 0x8d, 0xd1, 0xa1, 0x5f, 0xe5, 0x78, 0x38, 0x30, 0x1c, 0x85, 0x40,
		0xed, 0xb0, 0x25, 0x8c, 0x57, 0x30, 0x5e, 0x69, 0x30, 0x5e, 0xb1, 0x39, 0x35, 0x5e, 0x63, 0x66,
		0xb2, 0x2d, 0x34, 0x66, 0x68, 0xcc, 0xa5, 0xd7, 0x98, 0xc9, 0x41, 0x78, 0x49, 0x5c, 0xdd, 0x56,
		0x51, 0x99, 0x99, 0x41, 0x7a, 0x3b, 0xae, 0x33, 0xb7, 0xa1, 0x33, 0x6f, 0x8c, 0xb4, 0xd0, 0x90,
		0xa1, 0x21, 0x2f, 0x34, 0xe4, 0x70, 0xfd, 0x2e, 0x45, 0x2e, 0x86, 0x9e, 0x9c, 0x83, 0x59, 0x88,
		0xc1, 0x06, 0x02, 0x1d, 0x6c, 0x47, 0x5a, 0x8e, 0xf4, 0x9e, 0xe9, 0xc1, 0x0e, 0x61, 0x0b, 0x7a,
		0x1c, 0x6a, 0x0b, 0x01, 0x4a, 0x08, 0x50, 0x8a, 0xda, 0xf6, 0x4e, 0x4f, 0x18, 0x21, 0x4a, 0x94,
		0x80, 0x3d, 0x9e, 0xed, 0xae, 0xe4, 0xc9, 0x02, 0x2d, 0x24, 0x0b, 0x44, 0xea, 0x4c, 0xb6, 0x50,
		0x69, 0x07, 0x95, 0x76, 0x0e, 0x8a, 0x5d, 0x4e, 0xb9, 0x95, 0x76, 0x52, 0xb3, 0xf5, 0xb6, 0x59,
		0x69, 0x87, 0x34, 0x34, 0xda, 0x90, 0x28, 0x95, 0x76, 0x52, 0x02, 0xf7, 0xb3, 0x03, 0xf5, 0x37,
		0x52, 0x65, 0xa7, 0x94, 0x2f, 0x8b, 0x2f, 0xf2, 0xcd, 0xf0, 0x84, 0x5c, 0x09, 0x7a, 0x8e, 0x84,
		0xd6, 0x1a, 0x3b, 0x95, 0x7c, 0xdd, 0xbb, 0xce, 0x77, 0xbb, 0xef, 0x43, 0xfd, 0xf6, 0x9d, 0x7c,
		0x49, 0x0e, 0x5e, 0x2d, 0x59, 0x51, 0xcd, 0x1a, 0x69, 0xb8, 0xa8, 0xe0, 0xbe, 0x86, 0xc2, 0x7b,
		0x51, 0x0c, 0x01, 0x38, 0x0c, 0x1c, 0x06, 0x0e, 0x97, 0x10, 0x87, 0x51, 0x0e, 0x21, 0x18, 0xd6,
		0xee, 0x65, 0xbc, 0x02, 0x72, 0x75, 0x41, 0xee, 0x72, 0xdf, 0x8b, 0x1a, 0xee, 0x40, 0x5e, 0x2a,
		0x29, 0x50, 0xc3, 0x1d, 0x96, 0x65, 0x86, 0x65, 0x79, 0xb5, 0xee, 0xc3, 0xfa, 0x21, 0xdd, 0xa6,
		0xfc, 0x3e, 0x6c, 0xd3, 0x8f, 0x3d, 0xdc, 0x8a, 0x41, 0x99, 0x3a, 0x26, 0xca, 0x58, 0x28, 0xa6,
		0xe4, 0x47, 0xcb, 0x4d, 0xb6, 0x21, 0xfb, 0x3f, 0x6a, 0x30, 0x1e, 0xaf, 0x3f, 0xa6, 0x04, 0xc6,
		0x63, 0xbf, 0x53, 0x45, 0x19, 0x8f, 0xe3, 0x88, 0x4c, 0xa4, 0x82, 0x76, 0x73, 0x71, 0x72, 0x37,
		0x4a, 0x6c, 0x2e, 0x8e, 0x9d, 0xac, 0x0d, 0x99, 0x8b, 0x07, 0x96, 0x69, 0x8a, 0x81, 0x27, 0x9f,
		0xa4, 0xf7, 0xdc, 0x74, 0x85, 0xf3, 0x24, 0x07, 0x0c, 0x83, 0x45, 0x6c, 0xeb, 0x0a, 0x14, 0x69,
		0x4f, 0x67, 0x8b, 0x8a, 0x6a, 0xd1, 0xa9, 0x6c, 0x53, 0x8c, 0x16, 0x4d, 0x2f, 0xd3, 0x6e, 0x9b,
		0x4d, 0xe3, 0xe1, 0xce, 0x51, 0xa8, 0xd3, 0xbe, 0x68, 0xc9, 0x0b, 0xff, 0x6f, 0x97, 0x31, 0xfc,
		0x9f, 0xc6, 0x66, 0xaa, 0xec, 0x96, 0x9b, 0xed, 0x72, 0xb3, 0x9f, 0x3a, 0x1b, 0x32, 0x55, 0xd8,
		0x4d, 0x25, 0x00, 0x0c, 0xad, 0xaf, 0xe6, 0x58, 0x9a, 0x7f, 0xab, 0xc7, 0xfe, 0x87, 0x77, 0x60,
		0x52, 0x8c, 0x11, 0xc8, 0x56, 0xd4, 0x16, 0x65, 0xab, 0x29, 0x03, 0x3c, 0x51, 0xc8, 0x2b, 0x12,
		0x85, 0x89, 0x46, 0x61, 0x22, 0x92, 0x5f, 0x54, 0x78, 0x22, 0xa3, 0xb0, 0x5f, 0xae, 0x15, 0x97,
		0x66, 0x4b, 0x0a, 0xc5, 0x4b, 0xe2, 0xeb, 0x0b, 0xa4, 0xd9, 0xaa, 0xdd, 0x06, 0x69, 0xb6, 0x1b,
		0x27, 0x6d, 0xe7, 0xe4, 0xb2, 0x73, 0x79, 0x7e, 0x71, 0x72, 0x89, 0xd4, 0x81, 0xc2, 0xee, 0xcf,
		0x31, 0xe9, 0x4d, 0xec, 0x7c, 0xcb, 0xf5, 0xbc, 0x3d, 0x16, 0x6b, 0x2c, 0xd6, 0x58, 0xac, 0xb1,
		0x58, 0x63, 0xb1, 0xc6, 0x62, 0x8d, 0xc5, 0xba, 0xf2, 0x79, 0x7e, 0x8f, 0x96, 0x1b, 0xfe, 0xc5,
		0x99, 0x24, 0x7f, 0x62, 0x1a, 0x95, 0x6a, 0xeb, 0x2e, 0x89, 0x4f, 0x96, 0xdb, 0x5f, 0xfc, 0xfd,
		0x1c, 0x79, 0xc4, 0xe7, 0xe0, 0x09, 0xfd, 0x6b, 0xdb, 0xbc, 0xf6, 0x1f, 0xb0, 0x0b, 0xd9, 0x83,
		0x59, 0xe4, 0xe4, 0xbf, 0x9e, 0x28, 0x83, 0x7a, 0x1b, 0x79, 0x1d, 0xd1, 0x1e, 0xc4, 0x41, 0xc3,
		0x8c, 0xad, 0x26, 0x1f, 0x88, 0xbf, 0x2b, 0x72, 0xab, 0x82, 0x28, 0x90, 0x75, 0x52, 0x20, 0x0e,
		0x7a, 0x8e, 0xc2, 0x7b, 0x11, 0x07, 0x0d, 0x1c, 0x06, 0x0e, 0x03, 0x87, 0x4b, 0x88, 0xc3, 0x88,
		0x83, 0x0e, 0x86, 0xb5, 0x7b, 0x71, 0xd0, 0x80, 0x5c, 0x5d, 0x90, 0xfb, 0x68, 0xb9, 0x08, 0x80,
		0x06, 0xe4, 0x52, 0x49, 0x81, 0x00, 0x68, 0x04, 0x40, 0x33, 0x02, 0xa0, 0x23, 0xb6, 0x26, 0x7a,
		0xac, 0x73, 0xc4, 0x9c, 0xb4, 0x95, 0xb0, 0xe6, 0xe4, 0x0e, 0xc7, 0x77, 0x94, 0x12, 0xba, 0xec,
		0x4a, 0x2f, 0xa5, 0xfe, 0xc5, 0xec, 0x57, 0x0d, 0xc1, 0xcb, 0x31, 0xcf, 0xa9, 0x6d, 0x3f, 0x7a,
		0x79, 0xd6, 0xab, 0xa2, 0xc2, 0x97, 0x63, 0x09, 0x4d, 0x25, 0x44, 0x4d, 0x77, 0x00, 0x73, 0x4a,
		0x3f, 0x6a, 0xe5, 0x8d, 0x60, 0x8e, 0x9f, 0x30, 0x35, 0xd8, 0x44, 0xc5, 0x8b, 0x6c, 0x36, 0xa8,
		0xa8, 0xbe, 0x9b, 0xce, 0x26, 0xb0, 0x31, 0x40, 0xe1, 0x85, 0xad, 0x17, 0xb6, 0x5e, 0x20, 0x31,
		0x90, 0x18, 0x48, 0x0c, 0x24, 0x86, 0xb5, 0x97, 0x08, 0xc4, 0x84, 0xea, 0x7e, 0x6b, 0xa2, 0x46,
		0x4a, 0x39, 0x06, 0x08, 0xef, 0x21, 0x08, 0x8f, 0x85, 0x71, 0xef, 0x88, 0x7b, 0x0e, 0x0a, 0x5f,
		0xd0, 0x5e, 0xff, 0x1e, 0xe6, 0x88, 0x77, 0x57, 0xf3, 0xc4, 0x5f, 0x9f, 0xca, 0x61, 0x1d, 0x3e,
		0x11, 0x48, 0x45, 0xb9, 0x54, 0x13, 0xe9, 0xa1, 0x2e, 0x0c, 0x74, 0x13, 0x32, 0x29, 0xe0, 0x16,
		0x81, 0x5b, 0x84, 0xe1, 0x16, 0xf1, 0xe1, 0x65, 0xf9, 0x8f, 0xee, 0x19, 0xf9, 0x2c, 0x3d, 0xd1,
		0x0f, 0xff, 0x6d, 0xc5, 0x39, 0x92, 0xd6, 0xeb, 0xa4, 0xde, 0x52, 0x1c, 0x24, 0x13, 0x57, 0x34,
		0x07, 0x46, 0x5a, 0x91, 0xf0, 0xf0, 0x0a, 0x0d, 0x8e, 0x92, 0xc9, 0xa0, 0x7c, 0x6e, 0x92, 0xc9,
		0xa0, 0x30, 0x27, 0x49, 0x22, 0xb1, 0xa9, 0x44, 0xcf, 0x20, 0x3e, 0x59, 0x21, 0x62, 0x39, 0x4b,
		0x62, 0x27, 0x85, 0xab, 0xf6, 0x68, 0x76, 0x95, 0xc4, 0x4d, 0x9a, 0x1a, 0x90, 0x66, 0x3a, 0x4a,
		0x0c, 0xdb, 0x1e, 0xcb, 0x81, 0xc1, 0x73, 0x94, 0x44, 0x1b, 0x55, 0xa0, 0xb2, 0x4b, 0x2a, 0x0b,
		0x54, 0x54, 0x03, 0x4e, 0x63, 0x91, 0x62, 0xf4, 0x5f, 0x7a, 0x5d, 0x97, 0xf1, 0xd8, 0xfa, 0x2a,
		0x14, 0xde, 0xea, 0xba, 0x68, 0x48, 0xad, 0xe4, 0xb1, 0xcc, 0xb8, 0xf5, 0x89, 0xc6, 0x2c, 0x06,
		0xd3, 0x2a, 0x63, 0x31, 0x18, 0x12, 0x67, 0xaa, 0x72, 0x68, 0x6e, 0x4e, 0xcd, 0xcd, 0xb1, 0xca,
		0x9c, 0xcb, 0xd4, 0x5a, 0x89, 0x33, 0xc5, 0x4e, 0x8d, 0x0d, 0xe7, 0xe9, 0xce, 0xb2, 0xc6, 0xc2,
		0x30, 0x39, 0x93, 0xb5, 0x00, 0xbe, 0xb6, 0xc6, 0x17, 0x2c, 0x73, 0xc0, 0x3c, 0x07, 0xa8, 0x43,
		0xb4, 0x20, 0x5a, 0x85, 0x89, 0x16, 0xdd, 0x94, 0xa8, 0x62, 0x52, 0x5c, 0x37, 0x2d, 0x1a, 0xb6,
		0xdd, 0x8d, 0xb0, 0x7a, 0xec, 0xb9, 0x2c, 0xc9, 0x1b, 0x1f, 0xe7, 0xdb, 0x60, 0x86, 0xba, 0x45,
		0xda, 0x17, 0x2b, 0xed, 0x8f, 0x95, 0xf6, 0xc9, 0xbc, 0xfd, 0x32, 0x95, 0x2c, 0x39, 0x53, 0x59,
		0x17, 0xbb, 0x93, 0x98, 0x03, 0x1e, 0x06, 0xbe, 0xda, 0xb9, 0xfe, 0xcb, 0x15, 0x3f, 0x1b, 0xae,
		0xe8, 0xbf, 0xfe, 0xbc, 0x8e, 0xdc, 0x14, 0x49, 0xad, 0xd0, 0xe0, 0xb5, 0x69, 0xf0, 0x70, 0xae,
		0xc3, 0x80, 0xbd, 0x59, 0x52, 0x20, 0xcc, 0x69, 0x81, 0xc1, 0xb3, 0xf7, 0x22, 0x8e, 0x1c, 0x6b,
		0x62, 0x73, 0x40, 0x38, 0xd2, 0x0a, 0x76, 0x14, 0xd8, 0x51, 0x60, 0x47, 0xc1, 0x66, 0x0f, 0x76,
		0x94, 0xed, 0xdb, 0x51, 0x58, 0x70, 0x9e, 0x07, 0xd6, 0x21, 0x5c, 0x10, 0xae, 0xca, 0x5a, 0x52,
		0x86, 0xa3, 0x6e, 0x94, 0xd5, 0xe3, 0xce, 0x4b, 0x66, 0x48, 0xe1, 0x28, 0x5c, 0xb0, 0xa4, 0xe4,
		0xb2, 0xa4, 0x30, 0x41, 0x90, 0x68, 0x4a, 0x09, 0xde, 0x22, 0xfe, 0xeb, 0xec, 0xa6, 0xc8, 0x56,
		0x80, 0x1a, 0x0f, 0x63, 0x0a, 0x8c, 0x29, 0xbb, 0x62, 0x4c, 0x41, 0xa6, 0x42, 0x30, 0xac, 0xdd,
		0xcf, 0x54, 0x00, 0x00, 0xeb, 0x01, 0x60, 0x64, 0x29, 0x54, 0x25, 0x4b, 0x01, 0x12, 0xa1, 0x47,
		0x22, 0x16, 0xea, 0x39, 0xb2, 0x14, 0xa0, 0x97, 0x50, 0x49, 0xb1, 0x57, 0x59, 0x0a, 0x29, 0xa8,
		0x9b, 0xf6, 0x8a, 0xcb, 0x35, 0x41, 0xcb, 0x2e, 0x45, 0x07, 0x8f, 0x4e, 0x65, 0x71, 0x17, 0x1e,
		0x1d, 0x18, 0x9d, 0x61, 0x74, 0xae, 0x94, 0x47, 0x87, 0x02, 0xde, 0x0a, 0x20, 0x0e, 0x51, 0x82,
		0x28, 0x15, 0x26, 0x4a, 0xba, 0xfd, 0x37, 0x8f, 0x96, 0xdb, 0x9d, 0x57, 0x2d, 0x0c, 0x3f, 0x4b,
		0xe6, 0xb0, 0x21, 0xa8, 0x51, 0xf0, 0xd3, 0xc4, 0x5c, 0x4f, 0xf7, 0xd3, 0x10, 0x6b, 0x26, 0xd3,
		0xdc, 0x33, 0x9f, 0xb2, 0x6a, 0x15, 0xab, 0x69, 0xde, 0xa9, 0xd5, 0x19, 0xd7, 0xcd, 0xee, 0xd9,
		0x15, 0x0f, 0xa0, 0x7b, 0x43, 0xf7, 0x86, 0xee, 0x0d, 0x85, 0x01, 0xba, 0xb7, 0x0e, 0xdd, 0x9b,
		0x04, 0xdf, 0x2a, 0x30, 0x0e, 0x61, 0x82, 0x30, 0x55, 0x56, 0xfb, 0x76, 0xbd, 0x6e, 0x50, 0x15,
		0x63, 0xf9, 0x59, 0x32, 0xe5, 0x9b, 0xa2, 0x48, 0x41, 0xfb, 0xce, 0xa5, 0x7d, 0x53, 0xab, 0x73,
		0xd1, 0xd4, 0xef, 0xcf, 0x99, 0x55, 0xb1, 0xd4, 0xf4, 0xef, 0x27, 0xe9, 0xca, 0x3b, 0x39, 0x96,
		0xde, 0x33, 0x5d, 0x0b, 0x8f, 0xb4, 0x81, 0x2e, 0x0e, 0x5d, 0x1c, 0xba, 0x38, 0xd4, 0x07, 0xe8,
		0xe2, 0xdb, 0xd7, 0xc5, 0x19, 0x50, 0xae, 0x0e, 0xe9, 0x10, 0x2c, 0x08, 0x56, 0x65, 0xf5, 0xf2,
		0x27, 0xe9, 0x76, 0x97, 0x9c, 0x1e, 0x77, 0x5a, 0x32, 0x35, 0x9d, 0xae, 0x69, 0x41, 0x59, 0xcf,
		0xa5, 0xac, 0xb3, 0xf0, 0x8f, 0xa8, 0xb2, 0xff, 0xb5, 0xbc, 0x27, 0x0a, 0x6b, 0x6e, 0xab, 0xb0,
		0x66, 0xf2, 0x9c, 0xd3, 0x8b, 0x6c, 0x26, 0x4c, 0xf0, 0x56, 0xaa, 0x6d, 0x52, 0x86, 0x91, 0xde,
		0x7d, 0x4a, 0xed, 0xcd, 0x14, 0x55, 0x22, 0x5b, 0x65, 0xd8, 0x48, 0xfd, 0xcd, 0x27, 0xe9, 0x96,
		0xaf, 0x00, 0xa7, 0xdf, 0xa9, 0xa2, 0x2a, 0x70, 0x12, 0xb4, 0x37, 0xba, 0xb6, 0xa6, 0xb5, 0x0a,
		0x67, 0xfc, 0xd4, 0x70, 0xd5, 0x2b, 0xcd, 0x65, 0x38, 0x63, 0xa7, 0x4e, 0x0d, 0x77, 0xcb, 0x52,
		0x87, 0x73, 0xab, 0x51, 0xde, 0xe9, 0x4c, 0x50, 0x51, 0x33, 0x4b, 0x2a, 0x93, 0x14, 0xa3, 0xe8,
		0x95, 0x2f, 0xf3, 0xa1, 0x88, 0x22, 0x6a, 0xa8, 0x76, 0x05, 0x39, 0xd9, 0xb6, 0x9c, 0x20, 0x45,
		0x33, 0xb9, 0x19, 0x52, 0x21, 0xd6, 0x49, 0x81, 0x7a, 0x57, 0x73, 0x14, 0xde, 0x8b, 0x44, 0x79,
		0xe0, 0x30, 0x70, 0x18, 0x38, 0x5c, 0x42, 0x1c, 0x46, 0xaa, 0x7c, 0x30, 0xac, 0xdd, 0x4b, 0x04,
		0x06, 0xe4, 0xea, 0x82, 0xdc, 0xa5, 0x7d, 0x08, 0xc9, 0xc0, 0x40, 0x5e, 0x2a, 0x29, 0xf0, 0xca,
		0x32, 0x78, 0x56, 0x18, 0x9e, 0x95, 0x55, 0xcf, 0xe9, 0xfa, 0x21, 0xdd, 0xbf, 0xb2, 0x74, 0x94,
		0xf5, 0x63, 0x0f, 0xb7, 0xe2, 0x68, 0xa1, 0x8e, 0x89, 0x32, 0x96, 0x44, 0x97, 0xcb, 0x41, 0xa4,
		0xa3, 0x49, 0x1d, 0xac, 0x4b, 0xf7, 0x17, 0xe3, 0x6f, 0xf1, 0xa7, 0x65, 0xad, 0x2f, 0x53, 0xaf,
		0x3b, 0x5d, 0x8f, 0xfe, 0xb4, 0xd2, 0xaf, 0xa0, 0xba, 0x5a, 0xd0, 0x91, 0xe9, 0xc1, 0xf4, 0x7f,
		0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0xa3, 0x65, 0xff, 0x8c, 0x8b,
		0x01, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
}

