// Code generated by YGOT. DO NOT EDIT.
/*
Package ric_1_0_0 is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/adibrastegarnia/go/pkg/mod/github.com/openconfig/ygot@v0.6.1-0.20200103195725-e3c44fa43926/genutil/names.go
using the following YANG input files:
	- xapp@2020-11-18.yang
Imported modules were sourced from:
	- yang/...
*/
package ric_1_0_0

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Device represents the /device YANG schema element.
type Device struct {
	Xapps	*Xapp_Xapps	`path:"xapps" module:"xapp"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Xapp_Xapps represents the /xapp/xapps YANG schema element.
type Xapp_Xapps struct {
	Xapp	map[string]*Xapp_Xapps_Xapp	`path:"xapp" module:"xapp"`
}

// IsYANGGoStruct ensures that Xapp_Xapps implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Xapp_Xapps) IsYANGGoStruct() {}

// NewXapp creates a new entry in the Xapp list of the
// Xapp_Xapps struct. The keys of the list are populated from the input
// arguments.
func (t *Xapp_Xapps) NewXapp(Name string) (*Xapp_Xapps_Xapp, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Xapp == nil {
		t.Xapp = make(map[string]*Xapp_Xapps_Xapp)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Xapp[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Xapp", key)
	}

	t.Xapp[key] = &Xapp_Xapps_Xapp{
		Name: &Name,
	}

	return t.Xapp[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Xapp_Xapps) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Xapp_Xapps"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Xapp_Xapps) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Xapp_Xapps_Xapp represents the /xapp/xapps/xapp YANG schema element.
type Xapp_Xapps_Xapp struct {
	Name	*string	`path:"name" module:"xapp"`
	Version	*string	`path:"version" module:"xapp"`
}

// IsYANGGoStruct ensures that Xapp_Xapps_Xapp implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Xapp_Xapps_Xapp) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Xapp_Xapps_Xapp struct, which is a YANG list entry.
func (t *Xapp_Xapps_Xapp) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Xapp_Xapps_Xapp) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Xapp_Xapps_Xapp"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Xapp_Xapps_Xapp) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }



var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x4d, 0x6f, 0xe2, 0x30,
		0x10, 0xbd, 0xf3, 0x2b, 0xac, 0x39, 0x23, 0xc1, 0xde, 0x56, 0xb9, 0xb1, 0x4b, 0xab, 0x4a, 0x94,
		0xb6, 0x6a, 0x7b, 0xe8, 0xad, 0xb2, 0x92, 0x01, 0xac, 0x82, 0x63, 0xd9, 0x0e, 0x25, 0xaa, 0xf2,
		0xdf, 0xab, 0xc4, 0x21, 0xc5, 0xf9, 0x72, 0x9c, 0x4b, 0x2f, 0x5c, 0x2c, 0x98, 0x99, 0x64, 0xde,
		0xbc, 0xf7, 0xec, 0xf8, 0x6b, 0x42, 0x08, 0x21, 0xf0, 0x40, 0x0f, 0x08, 0x01, 0x81, 0x08, 0x8f,
		0x2c, 0x44, 0x98, 0x9a, 0xe8, 0x8a, 0xf1, 0x08, 0x02, 0xf2, 0xa7, 0xfc, 0xfb, 0x3f, 0xe6, 0x1b,
		0xb6, 0x85, 0x80, 0xcc, 0xcb, 0xc0, 0x92, 0x49, 0x08, 0x88, 0x79, 0x45, 0x11, 0x38, 0x51, 0x21,
		0x94, 0x15, 0xb2, 0xde, 0x6e, 0xd2, 0x53, 0x3b, 0x69, 0x37, 0xa9, 0xc2, 0xf5, 0x66, 0x55, 0xe2,
		0x49, 0xe2, 0x86, 0x9d, 0x1a, 0x4d, 0x1a, 0x8d, 0x6a, 0x7d, 0x8a, 0xfc, 0x4b, 0x9c, 0xc8, 0x10,
		0x5b, 0x9f, 0x35, 0x58, 0x30, 0xfd, 0x8c, 0x65, 0x0e, 0x07, 0x84, 0x69, 0x33, 0x6d, 0x2f, 0xbc,
		0xa3, 0x6a, 0x21, 0xb7, 0xc9, 0x01, 0xb9, 0x86, 0x80, 0x68, 0x99, 0x60, 0x47, 0xe1, 0x45, 0x95,
		0x41, 0xd5, 0x28, 0xcb, 0xac, 0x48, 0x56, 0x9b, 0xb6, 0x4e, 0xb1, 0x45, 0x75, 0xf7, 0x20, 0x0e,
		0x22, 0x7a, 0x88, 0x77, 0x0a, 0x30, 0x44, 0x08, 0x1f, 0x1c, 0x43, 0x84, 0xf1, 0x16, 0xc8, 0x5b,
		0x28, 0x0f, 0xc1, 0xda, 0x85, 0xeb, 0x10, 0xd0, 0x29, 0x64, 0x55, 0xc0, 0x0d, 0x55, 0x0e, 0x02,
		0xce, 0x84, 0x16, 0xd5, 0x8e, 0x51, 0x4a, 0x81, 0xe7, 0x8e, 0x32, 0x97, 0xd0, 0x3e, 0x82, 0xfb,
		0x0a, 0xef, 0x6b, 0x80, 0xd1, 0x46, 0x18, 0x6d, 0x88, 0x11, 0xc6, 0xe8, 0x37, 0x88, 0xc3, 0x28,
		0x55, 0xbf, 0xd7, 0x54, 0xa0, 0x1f, 0xd7, 0x4a, 0x4b, 0xc6, 0xb7, 0x43, 0xd8, 0x3e, 0x6f, 0xfd,
		0xbf, 0x93, 0x71, 0xf8, 0x7b, 0xb0, 0xc3, 0x11, 0xa5, 0x62, 0x31, 0x1f, 0x6e, 0xe5, 0xf3, 0x03,
		0x57, 0x37, 0x5f, 0xdd, 0xfc, 0x3b, 0x6e, 0xf6, 0x3a, 0xc8, 0x57, 0x98, 0x3a, 0x0e, 0x60, 0xb8,
		0x67, 0x4a, 0x2f, 0xb4, 0x76, 0x1c, 0xf8, 0x6b, 0xc6, 0x6f, 0xf6, 0x98, 0x8b, 0x90, 0x5f, 0x99,
		0x78, 0xb2, 0xdf, 0xf7, 0xec, 0xaa, 0x35, 0x3d, 0x0d, 0x2f, 0x7e, 0x94, 0x11, 0x4a, 0x8c, 0xfe,
		0xa5, 0x65, 0xa9, 0xd7, 0x7c, 0x0b, 0xce, 0x63, 0x4d, 0xb5, 0x6b, 0x0b, 0x83, 0x0a, 0x77, 0x78,
		0xa0, 0x82, 0xea, 0x5d, 0x4e, 0xc7, 0x2c, 0x37, 0x51, 0xb1, 0xa8, 0x99, 0xeb, 0x63, 0xaf, 0xb4,
		0x4c, 0x42, 0x5d, 0x7e, 0xef, 0xe0, 0x8d, 0x0a, 0xf1, 0x9e, 0x2f, 0xaa, 0x58, 0xdb, 0x8d, 0x98,
		0x79, 0x5e, 0x9b, 0x1c, 0x43, 0x74, 0x83, 0x6f, 0xbb, 0x35, 0x76, 0xe1, 0xb5, 0xa1, 0xfe, 0x00,
		0x32, 0xbf, 0x4a, 0x48, 0x5d, 0x50, 0x80, 0xa9, 0x5b, 0xfa, 0x81, 0xcf, 0x71, 0xdc, 0xdc, 0xb9,
		0x75, 0x78, 0x70, 0x99, 0xb2, 0xc0, 0x2c, 0xcd, 0x7d, 0xdd, 0x34, 0x9c, 0x64, 0xdf, 0x00, 0x00,
		0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x42, 0xf9, 0x04, 0xce, 0x0b, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
}

