#!/usr/bin/env bash

go run github.com/openconfig/ygot/generator -path=yang -output_file=testdevice_1_0_0/generated.go -package_name=testdevice_1_0_0 -generate_fakeroot test1@2018-02-20.yang

sedi=(-i)
case "$(uname)" in
  Darwin*) sedi=(-i "")
esac

lf=$'\n'; sed "${sedi[@]}" -e "1s/^/\/\/ Code generated by YGOT. DO NOT EDIT.\\$lf/" testdevice_1_0_0/generated.go


