#!/usr/bin/env bash

mkdir -p aether_2_1_0

go run github.com/openconfig/ygot/generator -path=../../../sdran-helm-charts/config-models/aether-2.1.x/files/yang \
       -output_file=aether_2_1_0/generated.go -package_name=aether_2_1_0 -generate_fakeroot --include_descriptions\
       aether-subscriber@2020-10-22.yang apn-profile@2021-03-04.yang up-profile@2020-10-22.yang qos-profile@2020-10-22.yang \
       access-profile@2020-10-22.yang security-profile@2020-11-30.yang enterprise@2020-11-30.yang connectivity-service@2021-03-18.yang \
       service-group@2021-03-04.yang service-policy@2021-03-04.yang service-rule@2021-03-04.yang


sedi=(-i)
case "$(uname)" in
  Darwin*) sedi=(-i "")
esac

lf=$'\n'; sed "${sedi[@]}" -e "1s/^/\/\/ Code generated by YGOT. DO NOT EDIT.\\$lf/" aether_2_1_0/generated.go


