# Code generated by model-compiler. DO NOT EDIT

FROM onosproject/golang-build:v1.0 as build

ENV GO111MODULE=on
COPY . /models/{{ .Name }}
RUN cd /models/{{ .Name }} && make build

FROM alpine:3.11
RUN apk add libc6-compat

USER nobody

COPY --from=build /models/{{ .Name }}/_bin/{{ .Name }} /usr/local/bin/{{ .Name }}

ENTRYPOINT ["{{ .Name }}"]
CMD ["5152"]