# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

# Code generated by model-compiler. DO NOT EDIT

FROM onosproject/golang-build:v1.0 as build

ENV GO111MODULE=on
COPY go.mod go.sum /models/{{ .Name }}/
COPY api /models/{{ .Name }}/api
COPY plugin /models/{{ .Name }}/plugin
RUN cd /models/{{ .Name }} && go build -o _bin/{{ .Name }} ./plugin

FROM alpine:3.14
RUN apk add libc6-compat

# Label image
ARG org_label_schema_version=unknown
ARG org_label_schema_vcs_url=unknown
ARG org_label_schema_vcs_ref=unknown
ARG org_label_schema_build_date=unknown
ARG org_opencord_vcs_commit_date=unknown
ARG org_opencord_vcs_dirty=unknown

LABEL \
org.label-schema.schema-version=1.0 \
org.label-schema.name={{ .Name }}-{{ .Version }} \
org.label-schema.version=$org_label_schema_version \
org.label-schema.vcs-url=$org_label_schema_vcs_url \
org.label-schema.vcs-ref=$org_label_schema_vcs_ref \
org.label-schema.build-date=$org_label_schema_build_date \
org.opencord.vcs-commit-date=$org_opencord_vcs_commit_date \
org.opencord.vcs-dirty=$org_opencord_vcs_dirty

USER nobody

COPY --from=build /models/{{ .Name }}/_bin/{{ .Name }} /usr/local/bin/{{ .Name }}

ENTRYPOINT ["{{ .Name }}"]
CMD ["5152"]