# Code generated by model-compiler. DO NOT EDIT.

export CGO_ENABLED=0
export GO111MODULE=on

image:
	docker build . -t onosproject/{{ .Name }}:{{ .Version }}

build:
	go mod tidy
	go build -o _bin/{{ .Name }}-{{ .Version }} ./plugin

