// Code generated by YGOT. DO NOT EDIT.
/*
Package plproxy_1_0_0 is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /root/go/pkg/mod/github.com/openconfig/ygot@v0.11.2/genutil/names.go
using the following YANG input files:
	- prom-label-proxy.yang
Imported modules were sourced from:
	- ../../../roc-helm-charts/config-models/plproxy-1.x/files/yang/...
*/
package plproxy_1_0_0

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Device represents the /device YANG schema element.
type Device struct {
	UserGroups	*PromLabelProxy_UserGroups	`path:"user-groups" module:"prom-label-proxy"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// PromLabelProxy_UserGroups represents the /prom-label-proxy/user-groups YANG schema element.
type PromLabelProxy_UserGroups struct {
	UserGroup	map[string]*PromLabelProxy_UserGroups_UserGroup	`path:"user-group" module:"prom-label-proxy"`
}

// IsYANGGoStruct ensures that PromLabelProxy_UserGroups implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*PromLabelProxy_UserGroups) IsYANGGoStruct() {}

// NewUserGroup creates a new entry in the UserGroup list of the
// PromLabelProxy_UserGroups struct. The keys of the list are populated from the input
// arguments.
func (t *PromLabelProxy_UserGroups) NewUserGroup(Name string) (*PromLabelProxy_UserGroups_UserGroup, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.UserGroup == nil {
		t.UserGroup = make(map[string]*PromLabelProxy_UserGroups_UserGroup)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.UserGroup[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list UserGroup", key)
	}

	t.UserGroup[key] = &PromLabelProxy_UserGroups_UserGroup{
		Name: &Name,
	}

	return t.UserGroup[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *PromLabelProxy_UserGroups) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["PromLabelProxy_UserGroups"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *PromLabelProxy_UserGroups) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// PromLabelProxy_UserGroups_UserGroup represents the /prom-label-proxy/user-groups/user-group YANG schema element.
type PromLabelProxy_UserGroups_UserGroup struct {
	Label	map[string]*PromLabelProxy_UserGroups_UserGroup_Label	`path:"label" module:"prom-label-proxy"`
	Name	*string	`path:"name" module:"prom-label-proxy"`
}

// IsYANGGoStruct ensures that PromLabelProxy_UserGroups_UserGroup implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*PromLabelProxy_UserGroups_UserGroup) IsYANGGoStruct() {}

// NewLabel creates a new entry in the Label list of the
// PromLabelProxy_UserGroups_UserGroup struct. The keys of the list are populated from the input
// arguments.
func (t *PromLabelProxy_UserGroups_UserGroup) NewLabel(Name string) (*PromLabelProxy_UserGroups_UserGroup_Label, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Label == nil {
		t.Label = make(map[string]*PromLabelProxy_UserGroups_UserGroup_Label)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Label[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Label", key)
	}

	t.Label[key] = &PromLabelProxy_UserGroups_UserGroup_Label{
		Name: &Name,
	}

	return t.Label[key], nil
}

// ΛListKeyMap returns the keys of the PromLabelProxy_UserGroups_UserGroup struct, which is a YANG list entry.
func (t *PromLabelProxy_UserGroups_UserGroup) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *PromLabelProxy_UserGroups_UserGroup) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["PromLabelProxy_UserGroups_UserGroup"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *PromLabelProxy_UserGroups_UserGroup) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// PromLabelProxy_UserGroups_UserGroup_Label represents the /prom-label-proxy/user-groups/user-group/label YANG schema element.
type PromLabelProxy_UserGroups_UserGroup_Label struct {
	Name	*string	`path:"name" module:"prom-label-proxy"`
	Value	*string	`path:"value" module:"prom-label-proxy"`
}

// IsYANGGoStruct ensures that PromLabelProxy_UserGroups_UserGroup_Label implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*PromLabelProxy_UserGroups_UserGroup_Label) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the PromLabelProxy_UserGroups_UserGroup_Label struct, which is a YANG list entry.
func (t *PromLabelProxy_UserGroups_UserGroup_Label) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *PromLabelProxy_UserGroups_UserGroup_Label) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["PromLabelProxy_UserGroups_UserGroup_Label"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *PromLabelProxy_UserGroups_UserGroup_Label) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }



var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4d, 0x8f, 0xda, 0x3c,
		0x10, 0xbe, 0xf3, 0x2b, 0x2c, 0x9f, 0x41, 0x80, 0x5e, 0x58, 0xf6, 0xe5, 0x46, 0x4b, 0x3f, 0xa4,
		0x5d, 0x5a, 0xd4, 0x6e, 0xcf, 0x2b, 0x6f, 0x32, 0x80, 0x55, 0x63, 0x47, 0xb6, 0x43, 0x41, 0x15,
		0xff, 0xbd, 0xca, 0x07, 0xd9, 0x24, 0x24, 0x64, 0x1c, 0xb6, 0x52, 0x0f, 0xdc, 0x82, 0x3d, 0x63,
		0xcf, 0xcc, 0xf3, 0xf8, 0xf1, 0xe0, 0xdf, 0x1d, 0x42, 0x08, 0xa1, 0x5f, 0xd8, 0x16, 0xe8, 0x94,
		0x50, 0x1f, 0x76, 0xdc, 0x03, 0xda, 0x4d, 0x46, 0x1f, 0xb8, 0xf4, 0xe9, 0x94, 0x0c, 0xd3, 0x9f,
		0xef, 0x95, 0x5c, 0xf1, 0x35, 0x9d, 0x92, 0x41, 0x3a, 0x30, 0xe7, 0x9a, 0x4e, 0x49, 0xb2, 0x44,
		0x3c, 0x10, 0x1a, 0xd0, 0xbd, 0xb5, 0x56, 0x61, 0x60, 0x0a, 0x13, 0x85, 0x3d, 0xf2, 0x46, 0xdd,
		0xa2, 0xc9, 0x1c, 0x8c, 0xa7, 0x79, 0x60, 0xb9, 0x92, 0x91, 0xe5, 0xd3, 0x06, 0x88, 0x55, 0x01,
		0x11, 0xb0, 0x03, 0x41, 0x3c, 0x25, 0x2d, 0xe3, 0x12, 0x74, 0xd9, 0xab, 0x18, 0x66, 0x36, 0x5c,
		0x0e, 0x37, 0x9b, 0x58, 0x6a, 0x58, 0xf1, 0xfd, 0x59, 0x80, 0x85, 0x20, 0x03, 0x11, 0x94, 0xb6,
		0x89, 0xa7, 0xbf, 0xab, 0x50, 0x7b, 0x50, 0xe9, 0x9a, 0x84, 0x02, 0x87, 0x5f, 0x4a, 0xfb, 0xf1,
		0x0a, 0xc9, 0x2e, 0xdd, 0x6a, 0xc3, 0xcf, 0xcc, 0xcc, 0xf4, 0x3a, 0xdc, 0x82, 0xb4, 0x74, 0x4a,
		0xac, 0x0e, 0xa1, 0xc6, 0x30, 0x67, 0x15, 0x07, 0x75, 0x66, 0x75, 0x2c, 0x8c, 0x1c, 0xcb, 0x15,
		0x2d, 0x41, 0x54, 0x01, 0x55, 0x7d, 0x36, 0xe7, 0x88, 0xd5, 0xa5, 0x53, 0x02, 0x6e, 0x46, 0x04,
		0x37, 0x96, 0xa8, 0x15, 0x89, 0x5c, 0x49, 0x25, 0xd8, 0x0d, 0xf0, 0x35, 0xc2, 0x88, 0x81, 0x13,
		0x09, 0x2b, 0x16, 0x5e, 0x67, 0x98, 0x9d, 0xe1, 0xc6, 0xc3, 0x5e, 0x0d, 0x7f, 0x0d, 0x0d, 0x1a,
		0xe9, 0x90, 0x19, 0x08, 0xf6, 0x02, 0xa2, 0xb9, 0x00, 0xa7, 0x7a, 0x26, 0xe6, 0x0d, 0xb9, 0xd4,
		0x92, 0x43, 0xb0, 0x17, 0x01, 0xa6, 0xc9, 0xfd, 0x32, 0x3f, 0xd0, 0x3c, 0x71, 0xe1, 0x8b, 0x23,
		0x6f, 0x5c, 0xf9, 0xd3, 0x9a, 0x47, 0xad, 0xf9, 0xe4, 0xce, 0xab, 0xcb, 0xfc, 0x6a, 0xe0, 0x19,
		0x9a, 0x6f, 0x99, 0xa1, 0x4c, 0x0a, 0x8d, 0xac, 0xdb, 0x09, 0x96, 0xd8, 0x0b, 0x99, 0x79, 0x4a,
		0xa3, 0x01, 0xd2, 0x1c, 0x4b, 0xa7, 0x36, 0xb4, 0x6a, 0x49, 0xaf, 0xb6, 0x34, 0xbb, 0x9a, 0x6e,
		0x57, 0xd3, 0xae, 0x3d, 0xfd, 0x70, 0x34, 0x44, 0xd2, 0x31, 0x0b, 0x63, 0xc1, 0xa4, 0xcf, 0xac,
		0xd2, 0x87, 0x66, 0x5d, 0xc9, 0x7c, 0x9e, 0x0e, 0x01, 0xb4, 0x43, 0xd7, 0x58, 0xcd, 0xe5, 0xda,
		0x05, 0xe0, 0x93, 0xe4, 0xdd, 0x77, 0xde, 0xa6, 0x36, 0x88, 0xba, 0xd0, 0x1d, 0x13, 0x61, 0x8b,
		0x23, 0x98, 0xb8, 0xdd, 0xce, 0xe0, 0xed, 0x0c, 0xde, 0xce, 0xe0, 0x5f, 0xbc, 0x48, 0x1f, 0xe0,
		0x80, 0xbc, 0xf0, 0xe8, 0x23, 0x37, 0x76, 0x66, 0x2d, 0xf2, 0xe2, 0x5d, 0x70, 0xf9, 0x41, 0x40,
		0xc4, 0x07, 0x83, 0x3b, 0x68, 0x74, 0xc1, 0xf6, 0x39, 0x8f, 0xe1, 0xfd, 0x68, 0x74, 0x37, 0x19,
		0x8d, 0x06, 0x93, 0xff, 0x26, 0x83, 0xff, 0xc7, 0xe3, 0xe1, 0xdd, 0x70, 0x8c, 0x58, 0xe4, 0xab,
		0xf6, 0x41, 0x83, 0xff, 0x2e, 0xca, 0x4a, 0x86, 0x42, 0x5c, 0x55, 0x9c, 0x99, 0x94, 0xca, 0xb2,
		0xb4, 0xbf, 0x44, 0xe4, 0x6c, 0xbc, 0x0d, 0x6c, 0x59, 0xc0, 0xec, 0x26, 0xaa, 0x69, 0x3f, 0xd0,
		0x6a, 0xdb, 0x8b, 0x3b, 0xd9, 0x5e, 0xa0, 0xd5, 0xfe, 0xd0, 0xcf, 0xfd, 0x43, 0xcd, 0x7d, 0xf7,
		0x31, 0xcd, 0x6e, 0xb2, 0xbe, 0xd5, 0xa1, 0x67, 0xd3, 0x96, 0x86, 0x2e, 0xb5, 0xda, 0x3e, 0x46,
		0xae, 0xcb, 0x68, 0xf1, 0xe7, 0x1f, 0x06, 0xf4, 0xa7, 0x78, 0xed, 0xd7, 0xcf, 0xe7, 0x78, 0xfe,
		0xf2, 0x49, 0xac, 0xe7, 0xcf, 0x85, 0xf2, 0xe0, 0xfa, 0x2a, 0x97, 0x7e, 0x0a, 0xa9, 0xe1, 0xb7,
		0x76, 0xfc, 0x5f, 0x6c, 0xc7, 0xd1, 0xfa, 0xe9, 0xae, 0x9b, 0x48, 0xbd, 0x3c, 0xbe, 0xd1, 0x1f,
		0xd9, 0x66, 0x3d, 0xc4, 0xe9, 0x20, 0x5e, 0xff, 0xae, 0xd2, 0x3d, 0x9c, 0xde, 0xd5, 0x25, 0x8b,
		0xd4, 0xb7, 0x96, 0xba, 0x76, 0xe9, 0x41, 0xc4, 0x59, 0xc9, 0xaa, 0x19, 0x7c, 0x74, 0x7c, 0xb5,
		0x6a, 0x48, 0xd8, 0x25, 0xd1, 0xaa, 0x57, 0x3c, 0x64, 0x56, 0xc5, 0x5c, 0x5e, 0x23, 0x4e, 0xbe,
		0xd2, 0x98, 0xeb, 0x62, 0xa5, 0xdc, 0x7c, 0x64, 0x3f, 0xe1, 0x9b, 0x52, 0xe7, 0x92, 0x50, 0x8e,
		0x9f, 0xe6, 0xa7, 0x0a, 0xb1, 0xcd, 0x93, 0xf7, 0xd8, 0x64, 0xc3, 0xce, 0xf1, 0x0f, 0x00, 0x00,
		0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x2b, 0x7b, 0x40, 0xae, 0x15, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
}

