// Code generated by YGOT. DO NOT EDIT.
/*
Package rbac_1_0_0 is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/adibrastegarnia/go/pkg/mod/github.com/openconfig/ygot@v0.8.12/genutil/names.go
using the following YANG input files:
	- rbac@2020-08-10.yang
Imported modules were sourced from:
	- yang/...
*/
package rbac_1_0_0

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Device represents the /device YANG schema element.
type Device struct {
	Rbac	*Rbac_Rbac	`path:"rbac" module:"rbac"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac represents the /rbac/rbac YANG schema element.
type Rbac_Rbac struct {
	Group	map[string]*Rbac_Rbac_Group	`path:"group" module:"rbac"`
	Role	map[string]*Rbac_Rbac_Role	`path:"role" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac) IsYANGGoStruct() {}

// NewGroup creates a new entry in the Group list of the
// Rbac_Rbac struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac) NewGroup(Groupid string) (*Rbac_Rbac_Group, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Group == nil {
		t.Group = make(map[string]*Rbac_Rbac_Group)
	}

	key := Groupid

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Group[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Group", key)
	}

	t.Group[key] = &Rbac_Rbac_Group{
		Groupid: &Groupid,
	}

	return t.Group[key], nil
}

// NewRole creates a new entry in the Role list of the
// Rbac_Rbac struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac) NewRole(Roleid string) (*Rbac_Rbac_Role, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Role == nil {
		t.Role = make(map[string]*Rbac_Rbac_Role)
	}

	key := Roleid

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Role[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Role", key)
	}

	t.Role[key] = &Rbac_Rbac_Role{
		Roleid: &Roleid,
	}

	return t.Role[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Group represents the /rbac/rbac/group YANG schema element.
type Rbac_Rbac_Group struct {
	Description	*string	`path:"description" module:"rbac"`
	Groupid	*string	`path:"groupid" module:"rbac"`
	Role	map[string]*Rbac_Rbac_Group_Role	`path:"role" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Group implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Group) IsYANGGoStruct() {}

// NewRole creates a new entry in the Role list of the
// Rbac_Rbac_Group struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac_Group) NewRole(Roleid string) (*Rbac_Rbac_Group_Role, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Role == nil {
		t.Role = make(map[string]*Rbac_Rbac_Group_Role)
	}

	key := Roleid

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Role[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Role", key)
	}

	t.Role[key] = &Rbac_Rbac_Group_Role{
		Roleid: &Roleid,
	}

	return t.Role[key], nil
}

// ΛListKeyMap returns the keys of the Rbac_Rbac_Group struct, which is a YANG list entry.
func (t *Rbac_Rbac_Group) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Groupid == nil {
		return nil, fmt.Errorf("nil value for key Groupid")
	}

	return map[string]interface{}{
		"groupid": *t.Groupid,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Group) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Group"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Group) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Group_Role represents the /rbac/rbac/group/role YANG schema element.
type Rbac_Rbac_Group_Role struct {
	Description	*string	`path:"description" module:"rbac"`
	Roleid	*string	`path:"roleid" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Group_Role implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Group_Role) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Rbac_Rbac_Group_Role struct, which is a YANG list entry.
func (t *Rbac_Rbac_Group_Role) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Roleid == nil {
		return nil, fmt.Errorf("nil value for key Roleid")
	}

	return map[string]interface{}{
		"roleid": *t.Roleid,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Group_Role) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Group_Role"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Group_Role) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Role represents the /rbac/rbac/role YANG schema element.
type Rbac_Rbac_Role struct {
	Description	*string	`path:"description" module:"rbac"`
	Permission	*Rbac_Rbac_Role_Permission	`path:"permission" module:"rbac"`
	Roleid	*string	`path:"roleid" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Role implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Role) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Rbac_Rbac_Role struct, which is a YANG list entry.
func (t *Rbac_Rbac_Role) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Roleid == nil {
		return nil, fmt.Errorf("nil value for key Roleid")
	}

	return map[string]interface{}{
		"roleid": *t.Roleid,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Role) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Role"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Role) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Role_Permission represents the /rbac/rbac/role/permission YANG schema element.
type Rbac_Rbac_Role_Permission struct {
	Noun	[]string	`path:"noun" module:"rbac"`
	Operation	E_RbacIdentities_PERMISSION	`path:"operation" module:"rbac"`
	Type	E_RbacIdentities_NOUNTYPE	`path:"type" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Role_Permission implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Role_Permission) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Role_Permission) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Role_Permission"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Role_Permission) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// E_RbacIdentities_NOUNTYPE is a derived int64 type which is used to represent
// the enumerated node RbacIdentities_NOUNTYPE. An additional value named
// RbacIdentities_NOUNTYPE_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_RbacIdentities_NOUNTYPE int64

// IsYANGGoEnum ensures that RbacIdentities_NOUNTYPE implements the yang.GoEnum
// interface. This ensures that RbacIdentities_NOUNTYPE can be identified as a
// mapped type for a YANG enumeration.
func (E_RbacIdentities_NOUNTYPE) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  RbacIdentities_NOUNTYPE.
func (E_RbacIdentities_NOUNTYPE) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_RbacIdentities_NOUNTYPE.
func (e E_RbacIdentities_NOUNTYPE) String() string {
	return ygot.EnumLogString(e, int64(e), "E_RbacIdentities_NOUNTYPE")
}

const (
	// RbacIdentities_NOUNTYPE_UNSET corresponds to the value UNSET of RbacIdentities_NOUNTYPE
	RbacIdentities_NOUNTYPE_UNSET E_RbacIdentities_NOUNTYPE = 0
	// RbacIdentities_NOUNTYPE_CONFIG corresponds to the value CONFIG of RbacIdentities_NOUNTYPE
	RbacIdentities_NOUNTYPE_CONFIG E_RbacIdentities_NOUNTYPE = 1
	// RbacIdentities_NOUNTYPE_GRPC corresponds to the value GRPC of RbacIdentities_NOUNTYPE
	RbacIdentities_NOUNTYPE_GRPC E_RbacIdentities_NOUNTYPE = 2
)


// E_RbacIdentities_PERMISSION is a derived int64 type which is used to represent
// the enumerated node RbacIdentities_PERMISSION. An additional value named
// RbacIdentities_PERMISSION_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_RbacIdentities_PERMISSION int64

// IsYANGGoEnum ensures that RbacIdentities_PERMISSION implements the yang.GoEnum
// interface. This ensures that RbacIdentities_PERMISSION can be identified as a
// mapped type for a YANG enumeration.
func (E_RbacIdentities_PERMISSION) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  RbacIdentities_PERMISSION.
func (E_RbacIdentities_PERMISSION) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

// String returns a logging-friendly string for E_RbacIdentities_PERMISSION.
func (e E_RbacIdentities_PERMISSION) String() string {
	return ygot.EnumLogString(e, int64(e), "E_RbacIdentities_PERMISSION")
}

const (
	// RbacIdentities_PERMISSION_UNSET corresponds to the value UNSET of RbacIdentities_PERMISSION
	RbacIdentities_PERMISSION_UNSET E_RbacIdentities_PERMISSION = 0
	// RbacIdentities_PERMISSION_ALL corresponds to the value ALL of RbacIdentities_PERMISSION
	RbacIdentities_PERMISSION_ALL E_RbacIdentities_PERMISSION = 1
	// RbacIdentities_PERMISSION_CREATE corresponds to the value CREATE of RbacIdentities_PERMISSION
	RbacIdentities_PERMISSION_CREATE E_RbacIdentities_PERMISSION = 2
	// RbacIdentities_PERMISSION_READ corresponds to the value READ of RbacIdentities_PERMISSION
	RbacIdentities_PERMISSION_READ E_RbacIdentities_PERMISSION = 3
)


// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_RbacIdentities_NOUNTYPE": {
		1: {Name: "CONFIG", DefiningModule: "rbac-identities"},
		2: {Name: "GRPC", DefiningModule: "rbac-identities"},
	},
	"E_RbacIdentities_PERMISSION": {
		1: {Name: "ALL", DefiningModule: "rbac-identities"},
		2: {Name: "CREATE", DefiningModule: "rbac-identities"},
		3: {Name: "READ", DefiningModule: "rbac-identities"},
	},
}


var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5c, 0x5f, 0x73, 0xe2, 0x36,
		0x10, 0x7f, 0xe7, 0x53, 0x78, 0xf4, 0xc8, 0x04, 0x63, 0x7a, 0xc9, 0xe5, 0x8e, 0x97, 0x0e, 0x97,
		0x90, 0x34, 0x73, 0x84, 0x30, 0x24, 0xed, 0xb4, 0xe5, 0x08, 0xa3, 0x03, 0xc1, 0x69, 0x6a, 0x64,
		0x46, 0x96, 0xdb, 0xd0, 0x86, 0xef, 0xde, 0xf1, 0x9f, 0x00, 0x0e, 0xfe, 0xb3, 0x92, 0x1d, 0x72,
		0x5c, 0xf4, 0x92, 0x21, 0xb6, 0x56, 0x5a, 0xef, 0xef, 0xa7, 0xdd, 0xd5, 0x4a, 0xf6, 0x7f, 0x15,
		0xc3, 0x30, 0x0c, 0xd4, 0xc5, 0x73, 0x82, 0x9a, 0x06, 0x9a, 0x90, 0xbf, 0xe9, 0x98, 0xa0, 0xa3,
		0xf0, 0xea, 0x67, 0xca, 0x26, 0xa8, 0x69, 0x34, 0xa2, 0x7f, 0xcf, 0x1c, 0x36, 0xa5, 0x33, 0xd4,
		0x34, 0xac, 0xe8, 0xc2, 0x39, 0xe5, 0xa8, 0x69, 0x84, 0x5d, 0x04, 0x17, 0xf8, 0x57, 0x3c, 0x8e,
		0x5d, 0x89, 0x75, 0x1e, 0xdc, 0x3d, 0x8a, 0xdf, 0x8b, 0x0f, 0xb1, 0xbe, 0xfc, 0x7c, 0xa8, 0xf5,
		0x8d, 0x1e, 0x27, 0x53, 0xfa, 0xb0, 0x33, 0x46, 0xde, 0x38, 0xc1, 0xfd, 0x5b, 0xc7, 0xe3, 0x63,
		0x92, 0x28, 0x1b, 0xea, 0x42, 0x96, 0xff, 0x38, 0xdc, 0x57, 0x07, 0x2d, 0xc2, 0x61, 0x8e, 0x92,
		0x1b, 0xfe, 0x82, 0xdd, 0x16, 0x9f, 0x79, 0x73, 0xc2, 0x04, 0x6a, 0x1a, 0x82, 0x7b, 0x24, 0xa5,
		0xe1, 0x56, 0xab, 0x50, 0xab, 0x9d, 0x66, 0xab, 0xd8, 0x95, 0xd5, 0xb3, 0xa7, 0x7d, 0x6e, 0xe0,
		0xf5, 0x8d, 0x19, 0x77, 0xbc, 0x45, 0xfa, 0x93, 0x3c, 0x59, 0x22, 0x6c, 0x96, 0xa2, 0x5c, 0xb2,
		0xe9, 0x73, 0x21, 0x80, 0x40, 0x01, 0x85, 0x04, 0x0a, 0x8d, 0x34, 0x44, 0xd2, 0x50, 0x49, 0x40,
		0x96, 0x0c, 0x5d, 0x0a, 0x84, 0xb9, 0x50, 0xae, 0x1b, 0x4c, 0x88, 0x3b, 0xe6, 0x74, 0x21, 0xa8,
		0xc3, 0xf2, 0xed, 0xb0, 0x99, 0xaf, 0x1b, 0xa1, 0x9c, 0x07, 0x8b, 0xe0, 0xb6, 0x72, 0x9a, 0xe5,
		0xc1, 0x2e, 0x03, 0xbf, 0x2c, 0x0d, 0x64, 0xe9, 0xa0, 0x4c, 0x0b, 0x65, 0x7a, 0x28, 0xd0, 0x24,
		0x9b, 0x2e, 0x39, 0xb4, 0x59, 0x8f, 0x77, 0xb7, 0x5c, 0x10, 0x39, 0x5b, 0xbb, 0x82, 0x53, 0x36,
		0x83, 0x58, 0xfb, 0xc9, 0x11, 0x7c, 0x00, 0xb4, 0xed, 0x10, 0x36, 0x13, 0xdf, 0x50, 0xd3, 0x18,
		0x80, 0xec, 0x04, 0xc3, 0x2f, 0xe8, 0xf9, 0x9a, 0x32, 0x30, 0xe0, 0x92, 0xa4, 0xde, 0x11, 0xfb,
		0x0d, 0xdb, 0x1e, 0x49, 0xf7, 0x7d, 0xa9, 0x72, 0x17, 0x1c, 0x8f, 0xfd, 0xb9, 0x76, 0x4e, 0x67,
		0x54, 0xb8, 0xfe, 0xc0, 0x60, 0xf9, 0xd5, 0x91, 0x84, 0x29, 0xf0, 0xc3, 0xfe, 0x4d, 0x61, 0x59,
		0x7b, 0x34, 0x46, 0xa5, 0x9c, 0x56, 0xc3, 0x8a, 0x9a, 0x7c, 0x06, 0x18, 0x61, 0xcc, 0xa4, 0x13,
		0xb8, 0x0f, 0x7e, 0x12, 0xd0, 0xfe, 0x57, 0xfb, 0xdf, 0x2d, 0x5b, 0x2f, 0x31, 0x9b, 0xd5, 0xe8,
		0x84, 0x30, 0x41, 0xa7, 0x94, 0x70, 0xed, 0x88, 0xdf, 0x98, 0x23, 0x7e, 0xa7, 0x68, 0x8a, 0x43,
		0x74, 0xc3, 0x00, 0xbe, 0xf6, 0xb0, 0x10, 0x84, 0x33, 0x30, 0x61, 0xd1, 0x00, 0xd7, 0xfe, 0x6d,
		0xd5, 0xfe, 0x1c, 0x0d, 0xa3, 0x1f, 0x56, 0xed, 0xe3, 0x97, 0x2f, 0xb5, 0x91, 0x39, 0xac, 0x42,
		0x9d, 0x8b, 0xf9, 0x68, 0x9a, 0x8f, 0x83, 0xfb, 0x87, 0xdf, 0x87, 0x66, 0xf5, 0xd1, 0x1c, 0xdc,
		0xcf, 0xaf, 0x83, 0x1f, 0xe6, 0xe0, 0xde, 0xee, 0x0c, 0xcd, 0x2a, 0x7a, 0x95, 0xf0, 0xc2, 0x1d,
		0x9b, 0xc0, 0x63, 0x4b, 0xd0, 0x1a, 0x16, 0x58, 0x1a, 0x3a, 0xb0, 0x1c, 0x62, 0x60, 0xc9, 0x5b,
		0x17, 0x2a, 0xad, 0x0f, 0x0b, 0xac, 0x13, 0x15, 0x3d, 0x3a, 0x98, 0x5e, 0x2a, 0x34, 0x53, 0xa5,
		0x9b, 0x2a, 0xed, 0x0a, 0xd3, 0xaf, 0x30, 0x0d, 0x0b, 0xd0, 0x51, 0xd2, 0xb9, 0x03, 0xd1, 0x02,
		0xe7, 0x3f, 0xea, 0xeb, 0x50, 0x95, 0x34, 0x48, 0x35, 0x1d, 0x92, 0x4f, 0x8b, 0x0a, 0xa5, 0x47,
		0x05, 0xd3, 0xa4, 0xa2, 0xe9, 0x52, 0x19, 0xb9, 0x82, 0x42, 0xfa, 0x54, 0x28, 0x8d, 0x2a, 0xdd,
		0x64, 0x96, 0xf5, 0x8a, 0x46, 0xab, 0xbc, 0x4c, 0xeb, 0x61, 0x49, 0x09, 0x1c, 0x00, 0xd4, 0x20,
		0x15, 0x01, 0x2c, 0x8b, 0x13, 0x53, 0x98, 0xdc, 0xd5, 0xb1, 0x8e, 0x3a, 0x3a, 0xea, 0x94, 0x1a,
		0x75, 0x6c, 0x82, 0xa7, 0x9c, 0x4c, 0x55, 0xc2, 0xce, 0xa9, 0x84, 0x4c, 0x0f, 0x07, 0x41, 0x07,
		0xd5, 0x7d, 0x2b, 0xd5, 0x7d, 0xaa, 0xd7, 0x23, 0xbe, 0x97, 0x35, 0x33, 0x0b, 0x25, 0x97, 0x9f,
		0xc9, 0x12, 0x3c, 0x05, 0x51, 0x87, 0xba, 0xa2, 0x25, 0x04, 0x30, 0x1d, 0xbd, 0xa6, 0xac, 0x6d,
		0x13, 0x9f, 0x24, 0x2e, 0x6c, 0xfa, 0xf9, 0x51, 0x60, 0x4b, 0xa2, 0xf1, 0xe1, 0xf8, 0xf8, 0xfd,
		0xe9, 0xf1, 0xb1, 0x75, 0xfa, 0xee, 0xd4, 0xfa, 0x78, 0x72, 0xd2, 0x78, 0xdf, 0x38, 0x01, 0x74,
		0x72, 0xc3, 0x27, 0x84, 0x93, 0xc9, 0x27, 0xff, 0xb9, 0x98, 0x67, 0xdb, 0x85, 0xcc, 0xd3, 0x62,
		0xcc, 0x11, 0x18, 0x9c, 0x51, 0x23, 0x77, 0xfc, 0x8d, 0xcc, 0xf1, 0x22, 0x8e, 0xb9, 0xff, 0x27,
		0x28, 0x01, 0xd6, 0x01, 0x8b, 0xb5, 0xb0, 0x1b, 0xc1, 0xbd, 0xb1, 0x60, 0x11, 0x53, 0xfb, 0x5f,
		0xf1, 0x78, 0x14, 0xfc, 0xb9, 0xf4, 0x7b, 0x19, 0xf5, 0xfd, 0x5e, 0x54, 0x17, 0x9e, 0x52, 0x5b,
		0x52, 0x11, 0x3b, 0xb2, 0xeb, 0x97, 0x30, 0x5a, 0xc0, 0xe9, 0x50, 0x88, 0x06, 0x30, 0xf8, 0xd3,
		0x9e, 0x17, 0x08, 0x77, 0x0e, 0xcc, 0x59, 0xdb, 0x98, 0x99, 0xc8, 0x26, 0x83, 0xba, 0x0b, 0x59,
		0x82, 0xfa, 0xd9, 0x55, 0x03, 0x48, 0xb5, 0x40, 0xef, 0xf6, 0x16, 0x0c, 0x74, 0x7a, 0xb7, 0x57,
		0x17, 0x85, 0xf4, 0x6e, 0x6f, 0x59, 0xab, 0x69, 0xbd, 0xc9, 0x50, 0x6c, 0x75, 0xac, 0x77, 0x7b,
		0x4b, 0x2a, 0xc7, 0x2f, 0x08, 0x9f, 0x53, 0xd7, 0x95, 0x72, 0xc3, 0x5b, 0x32, 0xba, 0x34, 0xaf,
		0x4b, 0xf3, 0x06, 0x62, 0x8e, 0xa7, 0x50, 0x93, 0x0f, 0xa4, 0x74, 0x59, 0x44, 0x97, 0x45, 0x74,
		0x31, 0x5e, 0x17, 0xe3, 0xdf, 0x56, 0x31, 0xfe, 0xa7, 0x1f, 0xb2, 0x18, 0x2f, 0x57, 0x37, 0x94,
		0x3a, 0x0d, 0xb1, 0x16, 0xac, 0xc7, 0x4e, 0x43, 0xd4, 0x47, 0x66, 0xf5, 0xe7, 0x61, 0x15, 0x95,
		0xbd, 0x61, 0x00, 0xf4, 0x43, 0x52, 0x15, 0x43, 0xf5, 0xca, 0x61, 0xa9, 0x15, 0x44, 0xb5, 0x4a,
		0xa2, 0x44, 0xc1, 0x16, 0x90, 0x6a, 0x39, 0x0b, 0xc2, 0xb1, 0xda, 0x46, 0xfe, 0x46, 0x54, 0x67,
		0x0e, 0x3a, 0x73, 0xd8, 0x63, 0xe6, 0x10, 0x9e, 0x64, 0x14, 0x4b, 0xc5, 0x4d, 0x15, 0x99, 0x99,
		0x79, 0x15, 0x0d, 0xf5, 0x09, 0xbb, 0x0a, 0x60, 0x3f, 0x29, 0xdc, 0x6b, 0xf7, 0xaf, 0xaf, 0x6e,
		0x6f, 0xaf, 0x6e, 0xba, 0x48, 0x65, 0x91, 0xec, 0x4a, 0xfb, 0x66, 0xb5, 0x14, 0x26, 0xa6, 0x73,
		0xab, 0xd3, 0x41, 0xfb, 0x48, 0x02, 0x0a, 0xaa, 0x79, 0xd6, 0x6f, 0xb7, 0xee, 0xda, 0x87, 0xa0,
		0x69, 0xbf, 0xdd, 0x3a, 0x47, 0x2f, 0x9c, 0x21, 0x0c, 0xf7, 0x5e, 0x08, 0x81, 0xc4, 0x18, 0x21,
		0x33, 0xd3, 0xd7, 0xf6, 0x0a, 0xa4, 0x74, 0x64, 0xd1, 0x91, 0x45, 0x47, 0x96, 0x74, 0x85, 0xbb,
		0x37, 0xbf, 0x76, 0xef, 0xfe, 0xe8, 0xb5, 0x0f, 0x27, 0xae, 0x9c, 0xdd, 0x74, 0x2f, 0xae, 0x2e,
		0x0f, 0xc1, 0x61, 0x5f, 0xf6, 0x7b, 0x67, 0x3f, 0xa0, 0xc3, 0xfe, 0x3e, 0x8e, 0x29, 0x04, 0xe7,
		0x53, 0xc0, 0xd5, 0x6b, 0x23, 0x6b, 0x47, 0xbb, 0xef, 0xd8, 0x64, 0xd4, 0xdb, 0x74, 0xf5, 0x42,
		0x27, 0xe5, 0x65, 0xde, 0xc3, 0x82, 0x9d, 0x72, 0xd1, 0x1b, 0xa3, 0x25, 0x46, 0x21, 0xfd, 0x1a,
		0x96, 0xde, 0x21, 0xd5, 0xaf, 0x61, 0x19, 0xfa, 0x35, 0xac, 0xac, 0x1e, 0x5e, 0xef, 0x35, 0x2c,
		0x95, 0xd3, 0x70, 0x99, 0x51, 0x44, 0x1f, 0x86, 0x8b, 0x27, 0x13, 0x2a, 0x67, 0xe1, 0xd2, 0xcf,
		0x37, 0xae, 0x24, 0xbf, 0x8e, 0x92, 0xf3, 0x08, 0xa9, 0xaa, 0x27, 0x7d, 0x1b, 0x26, 0x45, 0xdb,
		0xb8, 0xa2, 0x1b, 0x75, 0xc2, 0x5f, 0x91, 0x42, 0x69, 0x8a, 0x20, 0xea, 0x5e, 0xe0, 0xbf, 0x48,
		0xdf, 0x71, 0x76, 0xa3, 0xea, 0x73, 0xe5, 0xd0, 0xf6, 0xad, 0x98, 0x2e, 0xe7, 0xe1, 0x27, 0x79,
		0xc2, 0x01, 0x2b, 0xab, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x32,
		0xf6, 0x65, 0x50, 0xb1, 0x47, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
	"/rbac/role/permission/operation": []reflect.Type{
		reflect.TypeOf((E_RbacIdentities_PERMISSION)(0)),
	},
	"/rbac/role/permission/type": []reflect.Type{
		reflect.TypeOf((E_RbacIdentities_NOUNTYPE)(0)),
	},
}

