// Code generated by GENERATOR. DO NOT EDIT.
/*
Package rbac_1_0_0 is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /home/scondon/go/pkg/mod/github.com/openconfig/ygot@v0.6.1-0.20200103195725-e3c44fa43926/genutil/names.go
using the following YANG input files:
	- rbac@2020-08-10.yang
Imported modules were sourced from:
	- yang/...
*/
package rbac_1_0_0

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Device represents the /device YANG schema element.
type Device struct {
	Rbac	*Rbac_Rbac	`path:"rbac" module:"rbac"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac represents the /rbac/rbac YANG schema element.
type Rbac_Rbac struct {
	Group	map[string]*Rbac_Rbac_Group	`path:"group" module:"rbac"`
	Role	map[string]*Rbac_Rbac_Role	`path:"role" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac) IsYANGGoStruct() {}

// NewGroup creates a new entry in the Group list of the
// Rbac_Rbac struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac) NewGroup(Groupid string) (*Rbac_Rbac_Group, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Group == nil {
		t.Group = make(map[string]*Rbac_Rbac_Group)
	}

	key := Groupid

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Group[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Group", key)
	}

	t.Group[key] = &Rbac_Rbac_Group{
		Groupid: &Groupid,
	}

	return t.Group[key], nil
}

// NewRole creates a new entry in the Role list of the
// Rbac_Rbac struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac) NewRole(Roleid string) (*Rbac_Rbac_Role, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Role == nil {
		t.Role = make(map[string]*Rbac_Rbac_Role)
	}

	key := Roleid

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Role[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Role", key)
	}

	t.Role[key] = &Rbac_Rbac_Role{
		Roleid: &Roleid,
	}

	return t.Role[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Group represents the /rbac/rbac/group YANG schema element.
type Rbac_Rbac_Group struct {
	Description	*string	`path:"description" module:"rbac"`
	Groupid	*string	`path:"groupid" module:"rbac"`
	Role	map[string]*Rbac_Rbac_Group_Role	`path:"role" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Group implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Group) IsYANGGoStruct() {}

// NewRole creates a new entry in the Role list of the
// Rbac_Rbac_Group struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac_Group) NewRole(Roleid string) (*Rbac_Rbac_Group_Role, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Role == nil {
		t.Role = make(map[string]*Rbac_Rbac_Group_Role)
	}

	key := Roleid

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Role[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Role", key)
	}

	t.Role[key] = &Rbac_Rbac_Group_Role{
		Roleid: &Roleid,
	}

	return t.Role[key], nil
}

// ΛListKeyMap returns the keys of the Rbac_Rbac_Group struct, which is a YANG list entry.
func (t *Rbac_Rbac_Group) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Groupid == nil {
		return nil, fmt.Errorf("nil value for key Groupid")
	}

	return map[string]interface{}{
		"groupid": *t.Groupid,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Group) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Group"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Group) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Group_Role represents the /rbac/rbac/group/role YANG schema element.
type Rbac_Rbac_Group_Role struct {
	Description	*string	`path:"description" module:"rbac"`
	Roleid	*string	`path:"roleid" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Group_Role implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Group_Role) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Rbac_Rbac_Group_Role struct, which is a YANG list entry.
func (t *Rbac_Rbac_Group_Role) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Roleid == nil {
		return nil, fmt.Errorf("nil value for key Roleid")
	}

	return map[string]interface{}{
		"roleid": *t.Roleid,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Group_Role) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Group_Role"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Group_Role) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Role represents the /rbac/rbac/role YANG schema element.
type Rbac_Rbac_Role struct {
	Description	*string	`path:"description" module:"rbac"`
	Permission	*Rbac_Rbac_Role_Permission	`path:"permission" module:"rbac"`
	Roleid	*string	`path:"roleid" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Role implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Role) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Rbac_Rbac_Role struct, which is a YANG list entry.
func (t *Rbac_Rbac_Role) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Roleid == nil {
		return nil, fmt.Errorf("nil value for key Roleid")
	}

	return map[string]interface{}{
		"roleid": *t.Roleid,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Role) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Role"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Role) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Role_Permission represents the /rbac/rbac/role/permission YANG schema element.
type Rbac_Rbac_Role_Permission struct {
	Noun	[]string	`path:"noun" module:"rbac"`
	Operation	E_RbacIdentities_PERMISSION	`path:"operation" module:"rbac"`
	Type	E_RbacIdentities_NOUNTYPE	`path:"type" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Role_Permission implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Role_Permission) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Role_Permission) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Role_Permission"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Role_Permission) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// E_RbacIdentities_NOUNTYPE is a derived int64 type which is used to represent
// the enumerated node RbacIdentities_NOUNTYPE. An additional value named
// RbacIdentities_NOUNTYPE_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_RbacIdentities_NOUNTYPE int64

// IsYANGGoEnum ensures that RbacIdentities_NOUNTYPE implements the yang.GoEnum
// interface. This ensures that RbacIdentities_NOUNTYPE can be identified as a
// mapped type for a YANG enumeration.
func (E_RbacIdentities_NOUNTYPE) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  RbacIdentities_NOUNTYPE.
func (E_RbacIdentities_NOUNTYPE) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

const (
	// RbacIdentities_NOUNTYPE_UNSET corresponds to the value UNSET of RbacIdentities_NOUNTYPE
	RbacIdentities_NOUNTYPE_UNSET E_RbacIdentities_NOUNTYPE = 0
	// RbacIdentities_NOUNTYPE_CONFIG corresponds to the value CONFIG of RbacIdentities_NOUNTYPE
	RbacIdentities_NOUNTYPE_CONFIG E_RbacIdentities_NOUNTYPE = 1
	// RbacIdentities_NOUNTYPE_GRPC corresponds to the value GRPC of RbacIdentities_NOUNTYPE
	RbacIdentities_NOUNTYPE_GRPC E_RbacIdentities_NOUNTYPE = 2
)


// E_RbacIdentities_PERMISSION is a derived int64 type which is used to represent
// the enumerated node RbacIdentities_PERMISSION. An additional value named
// RbacIdentities_PERMISSION_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_RbacIdentities_PERMISSION int64

// IsYANGGoEnum ensures that RbacIdentities_PERMISSION implements the yang.GoEnum
// interface. This ensures that RbacIdentities_PERMISSION can be identified as a
// mapped type for a YANG enumeration.
func (E_RbacIdentities_PERMISSION) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  RbacIdentities_PERMISSION.
func (E_RbacIdentities_PERMISSION) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

const (
	// RbacIdentities_PERMISSION_UNSET corresponds to the value UNSET of RbacIdentities_PERMISSION
	RbacIdentities_PERMISSION_UNSET E_RbacIdentities_PERMISSION = 0
	// RbacIdentities_PERMISSION_ALL corresponds to the value ALL of RbacIdentities_PERMISSION
	RbacIdentities_PERMISSION_ALL E_RbacIdentities_PERMISSION = 1
	// RbacIdentities_PERMISSION_CREATE corresponds to the value CREATE of RbacIdentities_PERMISSION
	RbacIdentities_PERMISSION_CREATE E_RbacIdentities_PERMISSION = 2
	// RbacIdentities_PERMISSION_READ corresponds to the value READ of RbacIdentities_PERMISSION
	RbacIdentities_PERMISSION_READ E_RbacIdentities_PERMISSION = 3
)


// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_RbacIdentities_NOUNTYPE": {
		1: {Name: "CONFIG", DefiningModule: "rbac-identities"},
		2: {Name: "GRPC", DefiningModule: "rbac-identities"},
	},
	"E_RbacIdentities_PERMISSION": {
		1: {Name: "ALL", DefiningModule: "rbac-identities"},
		2: {Name: "CREATE", DefiningModule: "rbac-identities"},
		3: {Name: "READ", DefiningModule: "rbac-identities"},
	},
}


var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5c, 0xdd, 0x73, 0xe2, 0x36,
		0x10, 0x7f, 0xe7, 0xaf, 0xf0, 0xe8, 0x31, 0x13, 0x0c, 0xd7, 0x4e, 0xa7, 0x2d, 0x6f, 0x5c, 0x42,
		0xd2, 0xcc, 0x01, 0x61, 0x9c, 0xb4, 0xd3, 0x96, 0x23, 0x8c, 0xce, 0x08, 0x4e, 0x53, 0x23, 0x33,
		0xb2, 0xdc, 0x42, 0x1b, 0xfe, 0xf7, 0x8e, 0x3f, 0xf8, 0x30, 0xf8, 0x63, 0x25, 0x3b, 0xe4, 0x48,
		0xf4, 0x92, 0x21, 0x96, 0x56, 0x5a, 0xef, 0x6f, 0xbd, 0xbb, 0xda, 0x5d, 0xfb, 0xbf, 0x9a, 0x61,
		0x18, 0x06, 0xea, 0xe3, 0x39, 0x41, 0x2d, 0x03, 0x4d, 0xc8, 0xdf, 0xd4, 0x26, 0xe8, 0x32, 0xba,
		0xfa, 0x89, 0xb2, 0x09, 0x6a, 0x19, 0x1f, 0xe2, 0x7f, 0xaf, 0x5c, 0x36, 0xa5, 0x33, 0xd4, 0x32,
		0x9a, 0xf1, 0x85, 0x6b, 0xca, 0x51, 0xcb, 0x88, 0x96, 0x08, 0x2f, 0xf0, 0x2f, 0xd8, 0x4e, 0x5c,
		0x49, 0x2c, 0x1e, 0x8e, 0x5e, 0x26, 0xc7, 0x92, 0x5b, 0x6c, 0x2f, 0x1f, 0x6e, 0xb5, 0x1d, 0x18,
		0x70, 0x32, 0xa5, 0xcb, 0xa3, 0x3d, 0x8a, 0xf6, 0x09, 0xc7, 0x1f, 0x5c, 0x9f, 0xdb, 0x24, 0x95,
		0x36, 0xe2, 0x85, 0xac, 0xfe, 0x71, 0x79, 0xc0, 0x0e, 0x5a, 0x44, 0xdb, 0x5c, 0xa6, 0x4f, 0xfc,
		0x05, 0x7b, 0x6d, 0x3e, 0xf3, 0xe7, 0x84, 0x09, 0xd4, 0x32, 0x04, 0xf7, 0x49, 0xc6, 0xc4, 0xbd,
		0x59, 0x11, 0x57, 0x47, 0xd3, 0xd6, 0x89, 0x2b, 0xeb, 0x83, 0xbb, 0x3d, 0x14, 0xf0, 0x76, 0x60,
		0xc6, 0x5d, 0x7f, 0x91, 0x7d, 0x27, 0x1b, 0x49, 0x44, 0xd3, 0x32, 0x98, 0x4b, 0x17, 0x7d, 0x21,
		0x04, 0x10, 0x28, 0xa0, 0x90, 0x40, 0xa1, 0x91, 0x86, 0x48, 0x1a, 0x2a, 0x09, 0xc8, 0xd2, 0xa1,
		0xcb, 0x80, 0xb0, 0x10, 0xca, 0xed, 0x84, 0x09, 0xf1, 0x6c, 0x4e, 0x17, 0x82, 0xba, 0xac, 0x58,
		0x0e, 0xbb, 0xe7, 0x75, 0x47, 0x54, 0x70, 0x63, 0x31, 0xdc, 0xcd, 0x82, 0x69, 0x45, 0xb0, 0xcb,
		0xc0, 0x2f, 0xab, 0x06, 0xb2, 0xea, 0xa0, 0xac, 0x16, 0xca, 0xea, 0xa1, 0xa0, 0x26, 0xf9, 0xea,
		0x52, 0xa0, 0x36, 0xdb, 0xfd, 0x1e, 0x57, 0x0b, 0x22, 0x27, 0x6b, 0x4f, 0x70, 0xca, 0x66, 0x10,
		0x69, 0x6f, 0x0c, 0xc1, 0x4f, 0x80, 0xb9, 0x5d, 0xc2, 0x66, 0xe2, 0x2b, 0x6a, 0x19, 0x43, 0x90,
		0x9c, 0x60, 0xf8, 0x85, 0x2b, 0xf7, 0x28, 0x03, 0x03, 0x2e, 0xa9, 0xd4, 0x47, 0x64, 0xbf, 0x61,
		0xc7, 0x27, 0xd9, 0xb6, 0x2f, 0x93, 0xee, 0x86, 0x63, 0x3b, 0x78, 0xd6, 0xae, 0xe9, 0x8c, 0x0a,
		0x2f, 0xd8, 0x18, 0x4c, 0xbf, 0xbe, 0x94, 0x10, 0x05, 0x5e, 0x9e, 0x5e, 0x14, 0xcd, 0xe6, 0x09,
		0x85, 0x51, 0xab, 0x66, 0xd6, 0xa8, 0xa6, 0x46, 0x9f, 0x03, 0x46, 0xe4, 0x33, 0xe9, 0x04, 0x6e,
		0x83, 0x37, 0x04, 0xda, 0xfe, 0x6a, 0xfb, 0xbb, 0x27, 0xeb, 0x15, 0x66, 0xb3, 0x3a, 0x9d, 0x10,
		0x26, 0xe8, 0x94, 0x12, 0xae, 0x0d, 0xf1, 0x3b, 0x33, 0xc4, 0xdf, 0x2b, 0x8a, 0xe2, 0x1c, 0xcd,
		0x30, 0x40, 0x5f, 0x07, 0x58, 0x08, 0xc2, 0x19, 0x58, 0x61, 0xd1, 0x10, 0xd7, 0xff, 0x6d, 0xd7,
		0xff, 0x1c, 0x8f, 0xe2, 0x1f, 0xcd, 0xfa, 0xcf, 0x9f, 0x3f, 0xd7, 0xc7, 0xe6, 0xe8, 0x02, 0x6a,
		0x5c, 0xcc, 0x67, 0xd3, 0x7c, 0x1e, 0x3e, 0x2d, 0x7f, 0x1f, 0x99, 0x17, 0xcf, 0xe6, 0xf0, 0x69,
		0xde, 0x0b, 0x7f, 0x98, 0xc3, 0x27, 0xa7, 0x3b, 0x32, 0x2f, 0xd0, 0xab, 0xb8, 0x17, 0xee, 0x3a,
		0x04, 0xee, 0x5b, 0xc2, 0xd9, 0x30, 0xc7, 0xf2, 0x41, 0x3b, 0x96, 0x73, 0x74, 0x2c, 0x45, 0xe7,
		0x42, 0xa5, 0xf3, 0x61, 0x89, 0x73, 0xa2, 0xa2, 0x45, 0x07, 0xab, 0x97, 0x8a, 0x9a, 0xa9, 0xaa,
		0x9b, 0xaa, 0xda, 0x95, 0x56, 0xbf, 0xd2, 0x6a, 0x58, 0x42, 0x1d, 0x25, 0x8d, 0x3b, 0x10, 0x2d,
		0x70, 0xfc, 0xa3, 0x7e, 0x0e, 0x55, 0x09, 0x83, 0x54, 0xc3, 0x21, 0xf9, 0xb0, 0xa8, 0x54, 0x78,
		0x54, 0x32, 0x4c, 0x2a, 0x1b, 0x2e, 0x55, 0x11, 0x2b, 0x28, 0x84, 0x4f, 0xa5, 0xc2, 0xa8, 0xca,
		0x45, 0xd6, 0x6c, 0xbe, 0xa2, 0xd0, 0x6a, 0x2f, 0x33, 0x7b, 0x54, 0x51, 0x00, 0x07, 0x00, 0x35,
		0x0c, 0x45, 0x00, 0xc7, 0xe2, 0xd4, 0x10, 0xa6, 0xf0, 0x74, 0xac, 0xbd, 0x8e, 0xf6, 0x3a, 0x95,
		0x7a, 0x1d, 0x87, 0xe0, 0x29, 0x27, 0x53, 0x15, 0xb7, 0xf3, 0xa3, 0x04, 0xcd, 0x00, 0x87, 0x4e,
		0x07, 0x35, 0x02, 0x29, 0x35, 0x02, 0x55, 0x6f, 0xc4, 0xfa, 0x5e, 0xd5, 0x93, 0x59, 0x2a, 0xb8,
		0xfc, 0x44, 0x56, 0xe0, 0x47, 0x10, 0x75, 0xa9, 0x27, 0xda, 0x42, 0x00, 0xc3, 0xd1, 0x1e, 0x65,
		0x1d, 0x87, 0x04, 0x4a, 0x12, 0x98, 0x44, 0xe6, 0x3b, 0x0e, 0xc0, 0x86, 0xf4, 0xf0, 0x52, 0x9e,
		0xe8, 0x9e, 0x4f, 0x08, 0x27, 0x93, 0x8f, 0xab, 0x98, 0xa4, 0x94, 0x44, 0xda, 0x8c, 0xb9, 0x02,
		0x83, 0x83, 0x68, 0xe4, 0xd9, 0x5f, 0xc9, 0x1c, 0x2f, 0x92, 0x30, 0x07, 0x7f, 0xc2, 0xac, 0x5f,
		0x03, 0x70, 0x3e, 0x8b, 0x96, 0x11, 0xdc, 0xb7, 0x05, 0x8b, 0x95, 0xd3, 0xfa, 0x82, 0xed, 0x71,
		0xf8, 0xe7, 0x36, 0x58, 0x65, 0x6c, 0x05, 0xab, 0xa8, 0x9e, 0x35, 0xa5, 0xaa, 0x50, 0xb1, 0x42,
		0xe4, 0xa7, 0x2c, 0x61, 0x9a, 0x20, 0xa5, 0x01, 0x52, 0xc8, 0xc3, 0x10, 0xcf, 0xba, 0x45, 0x20,
		0xc2, 0x05, 0xc8, 0xe6, 0x15, 0x2b, 0x73, 0xc1, 0x4c, 0xc7, 0xf1, 0x18, 0xa5, 0x14, 0xf6, 0xf3,
		0x73, 0x03, 0x90, 0x9c, 0x80, 0xae, 0xe9, 0x96, 0x74, 0x67, 0xba, 0xa6, 0xab, 0x53, 0x3f, 0xba,
		0xa6, 0x5b, 0xd5, 0x99, 0x59, 0x97, 0x12, 0xca, 0x9d, 0x81, 0x75, 0x4d, 0xb7, 0xa2, 0xa4, 0xfb,
		0x82, 0xf0, 0x39, 0xf5, 0x3c, 0x29, 0x33, 0xbc, 0x47, 0xa3, 0x13, 0xf0, 0x3a, 0x01, 0x6f, 0x20,
		0xe6, 0xfa, 0x0a, 0x99, 0xf7, 0x90, 0x4a, 0x27, 0x3f, 0x74, 0xf2, 0x43, 0xa7, 0xdc, 0x75, 0xca,
		0xfd, 0x7d, 0xa5, 0xdc, 0xbf, 0x7b, 0x93, 0x29, 0x77, 0xb9, 0xec, 0xa0, 0x54, 0xcf, 0xc3, 0x96,
		0xb0, 0x91, 0xe8, 0x79, 0x68, 0x84, 0x4d, 0x0f, 0x55, 0x17, 0x05, 0x80, 0x56, 0x48, 0x2a, 0x2b,
		0x58, 0x2a, 0x3b, 0x58, 0x2a, 0x4b, 0xa8, 0x96, 0x2d, 0x94, 0xc8, 0xc3, 0x02, 0x62, 0x2b, 0x77,
		0x41, 0x38, 0x56, 0xab, 0xcf, 0xef, 0x48, 0x75, 0xa8, 0xa0, 0x43, 0x85, 0x13, 0x86, 0x0a, 0x51,
		0x83, 0xa2, 0x58, 0x29, 0xd6, 0x4a, 0x7e, 0x90, 0xa0, 0xb9, 0x8b, 0xb7, 0xfa, 0x88, 0x3d, 0x05,
		0xb0, 0x37, 0x0c, 0x0f, 0x3a, 0x56, 0xef, 0xee, 0xe1, 0xe1, 0xee, 0xbe, 0x8f, 0x54, 0x4e, 0xc5,
		0x9e, 0xb4, 0x31, 0x56, 0x8b, 0x59, 0x12, 0x3c, 0xb7, 0xbb, 0x5d, 0x74, 0x0a, 0xaf, 0x5f, 0x92,
		0xcd, 0x2b, 0xab, 0xd3, 0x7e, 0xec, 0x9c, 0x03, 0xa7, 0x56, 0xa7, 0x7d, 0x8d, 0x5e, 0x38, 0x24,
		0x18, 0x9d, 0x3c, 0xf3, 0x01, 0xf1, 0x31, 0x42, 0xe6, 0x49, 0xdf, 0xca, 0x2b, 0xa4, 0xd2, 0x9e,
		0x45, 0x7b, 0x16, 0xed, 0x59, 0xb2, 0x19, 0xee, 0xdf, 0xff, 0xda, 0x7f, 0xfc, 0x63, 0xd0, 0x39,
		0x1f, 0xbf, 0x72, 0x75, 0xdf, 0xbf, 0xb9, 0xbb, 0x3d, 0x07, 0x83, 0x7d, 0x6b, 0x0d, 0xae, 0xde,
		0xa0, 0xc1, 0xfe, 0x36, 0x5a, 0x11, 0xc2, 0xb6, 0x13, 0x70, 0xba, 0xda, 0xc8, 0x2b, 0x61, 0x5b,
		0xae, 0x43, 0xc6, 0x83, 0xdd, 0x52, 0x2f, 0xd4, 0x00, 0x2f, 0xf3, 0x7a, 0x15, 0xac, 0x79, 0x45,
		0x57, 0x42, 0x2b, 0xf4, 0x42, 0xfa, 0xed, 0x2a, 0x5d, 0x12, 0xd5, 0x6f, 0x57, 0x19, 0xfa, 0xed,
		0xaa, 0xbc, 0x15, 0x5e, 0xef, 0xed, 0x2a, 0x95, 0x8e, 0xb7, 0x5c, 0x2f, 0xf2, 0xce, 0x1b, 0xde,
		0x0a, 0x9a, 0x18, 0x73, 0x83, 0x05, 0x70, 0xbb, 0x5b, 0xee, 0x77, 0x4e, 0x0a, 0x6e, 0x21, 0x93,
		0xf5, 0xb4, 0xaf, 0xbc, 0x64, 0x70, 0x9b, 0x64, 0x74, 0xc7, 0x4e, 0xf4, 0x2b, 0x66, 0x28, 0x8b,
		0x11, 0x44, 0xbd, 0x1b, 0xfc, 0x17, 0xb1, 0x5c, 0xf7, 0xd8, 0x91, 0x1e, 0x32, 0x87, 0xf6, 0x87,
		0x12, 0xbc, 0x5c, 0x47, 0x1f, 0xd7, 0x89, 0x36, 0xac, 0xad, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff,
		0x01, 0x00, 0x00, 0xff, 0xff, 0x10, 0xec, 0x7d, 0x17, 0x7b, 0x47, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
	"/rbac/role/permission/operation": []reflect.Type{
		reflect.TypeOf((E_RbacIdentities_PERMISSION)(0)),
	},
	"/rbac/role/permission/type": []reflect.Type{
		reflect.TypeOf((E_RbacIdentities_NOUNTYPE)(0)),
	},
}

