/*
Package rbac_1_0_0 is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /home/scondon/go/pkg/mod/github.com/openconfig/ygot@v0.6.1-0.20200103195725-e3c44fa43926/genutil/names.go
using the following YANG input files:
	- rbac@2020-08-10.yang
Imported modules were sourced from:
	- yang/...
*/
package rbac_1_0_0

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " +  err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root: &Device{},
		SchemaTree: uzp,
		Unmarshal: Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.GoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn )
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Device represents the /device YANG schema element.
type Device struct {
	Rbac	*Rbac_Rbac	`path:"rbac" module:"rbac"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac represents the /rbac/rbac YANG schema element.
type Rbac_Rbac struct {
	Group	map[string]*Rbac_Rbac_Group	`path:"group" module:"rbac"`
	Role	map[string]*Rbac_Rbac_Role	`path:"role" module:"rbac"`
	RoleBinding	map[Rbac_Rbac_RoleBinding_Key]*Rbac_Rbac_RoleBinding	`path:"role-binding" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac) IsYANGGoStruct() {}

// Rbac_Rbac_RoleBinding_Key represents the key for list RoleBinding of element /rbac/rbac.
type Rbac_Rbac_RoleBinding_Key struct {
	Role	string	`path:"role"`
	Group	string	`path:"group"`
}

// NewGroup creates a new entry in the Group list of the
// Rbac_Rbac struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac) NewGroup(Groupid string) (*Rbac_Rbac_Group, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Group == nil {
		t.Group = make(map[string]*Rbac_Rbac_Group)
	}

	key := Groupid

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Group[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Group", key)
	}

	t.Group[key] = &Rbac_Rbac_Group{
		Groupid: &Groupid,
	}

	return t.Group[key], nil
}

// NewRole creates a new entry in the Role list of the
// Rbac_Rbac struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac) NewRole(Roleid string) (*Rbac_Rbac_Role, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Role == nil {
		t.Role = make(map[string]*Rbac_Rbac_Role)
	}

	key := Roleid

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Role[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Role", key)
	}

	t.Role[key] = &Rbac_Rbac_Role{
		Roleid: &Roleid,
	}

	return t.Role[key], nil
}

// NewRoleBinding creates a new entry in the RoleBinding list of the
// Rbac_Rbac struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac) NewRoleBinding(Role string, Group string) (*Rbac_Rbac_RoleBinding, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.RoleBinding == nil {
		t.RoleBinding = make(map[Rbac_Rbac_RoleBinding_Key]*Rbac_Rbac_RoleBinding)
	}

	key := Rbac_Rbac_RoleBinding_Key{
		Role: Role,
		Group: Group,
	}

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.RoleBinding[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list RoleBinding", key)
	}

	t.RoleBinding[key] = &Rbac_Rbac_RoleBinding{
		Role: &Role,
		Group: &Group,
	}

	return t.RoleBinding[key], nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Group represents the /rbac/rbac/group YANG schema element.
type Rbac_Rbac_Group struct {
	Description	*string	`path:"description" module:"rbac"`
	Groupid	*string	`path:"groupid" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Group implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Group) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Rbac_Rbac_Group struct, which is a YANG list entry.
func (t *Rbac_Rbac_Group) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Groupid == nil {
		return nil, fmt.Errorf("nil value for key Groupid")
	}

	return map[string]interface{}{
		"groupid": *t.Groupid,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Group) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Group"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Group) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_Role represents the /rbac/rbac/role YANG schema element.
type Rbac_Rbac_Role struct {
	Description	*string	`path:"description" module:"rbac"`
	Roleid	*string	`path:"roleid" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_Role implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_Role) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Rbac_Rbac_Role struct, which is a YANG list entry.
func (t *Rbac_Rbac_Role) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Roleid == nil {
		return nil, fmt.Errorf("nil value for key Roleid")
	}

	return map[string]interface{}{
		"roleid": *t.Roleid,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_Role) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_Role"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_Role) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_RoleBinding represents the /rbac/rbac/role-binding YANG schema element.
type Rbac_Rbac_RoleBinding struct {
	Description	*string	`path:"description" module:"rbac"`
	Group	*string	`path:"group" module:"rbac"`
	Noun	map[string]*Rbac_Rbac_RoleBinding_Noun	`path:"noun" module:"rbac"`
	Role	*string	`path:"role" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_RoleBinding implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_RoleBinding) IsYANGGoStruct() {}

// NewNoun creates a new entry in the Noun list of the
// Rbac_Rbac_RoleBinding struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac_RoleBinding) NewNoun(Name string) (*Rbac_Rbac_RoleBinding_Noun, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Noun == nil {
		t.Noun = make(map[string]*Rbac_Rbac_RoleBinding_Noun)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Noun[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Noun", key)
	}

	t.Noun[key] = &Rbac_Rbac_RoleBinding_Noun{
		Name: &Name,
	}

	return t.Noun[key], nil
}

// ΛListKeyMap returns the keys of the Rbac_Rbac_RoleBinding struct, which is a YANG list entry.
func (t *Rbac_Rbac_RoleBinding) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Group == nil {
		return nil, fmt.Errorf("nil value for key Group")
	}

	if t.Role == nil {
		return nil, fmt.Errorf("nil value for key Role")
	}

	return map[string]interface{}{
		"group": *t.Group,
		"role": *t.Role,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_RoleBinding) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_RoleBinding"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_RoleBinding) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_RoleBinding_Noun represents the /rbac/rbac/role-binding/noun YANG schema element.
type Rbac_Rbac_RoleBinding_Noun struct {
	Name	*string	`path:"name" module:"rbac"`
	Type	E_RbacIdentities_NOUNTYPE	`path:"type" module:"rbac"`
	Verb	map[E_RbacIdentities_VERB]*Rbac_Rbac_RoleBinding_Noun_Verb	`path:"verb" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_RoleBinding_Noun implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_RoleBinding_Noun) IsYANGGoStruct() {}

// NewVerb creates a new entry in the Verb list of the
// Rbac_Rbac_RoleBinding_Noun struct. The keys of the list are populated from the input
// arguments.
func (t *Rbac_Rbac_RoleBinding_Noun) NewVerb(Verb E_RbacIdentities_VERB) (*Rbac_Rbac_RoleBinding_Noun_Verb, error){

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.Verb == nil {
		t.Verb = make(map[E_RbacIdentities_VERB]*Rbac_Rbac_RoleBinding_Noun_Verb)
	}

	key := Verb

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.Verb[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list Verb", key)
	}

	t.Verb[key] = &Rbac_Rbac_RoleBinding_Noun_Verb{
		Verb: Verb,
	}

	return t.Verb[key], nil
}

// ΛListKeyMap returns the keys of the Rbac_Rbac_RoleBinding_Noun struct, which is a YANG list entry.
func (t *Rbac_Rbac_RoleBinding_Noun) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_RoleBinding_Noun) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_RoleBinding_Noun"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_RoleBinding_Noun) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// Rbac_Rbac_RoleBinding_Noun_Verb represents the /rbac/rbac/role-binding/noun/verb YANG schema element.
type Rbac_Rbac_RoleBinding_Noun_Verb struct {
	Comment	*string	`path:"comment" module:"rbac"`
	Verb	E_RbacIdentities_VERB	`path:"verb" module:"rbac"`
}

// IsYANGGoStruct ensures that Rbac_Rbac_RoleBinding_Noun_Verb implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Rbac_Rbac_RoleBinding_Noun_Verb) IsYANGGoStruct() {}

// ΛListKeyMap returns the keys of the Rbac_Rbac_RoleBinding_Noun_Verb struct, which is a YANG list entry.
func (t *Rbac_Rbac_RoleBinding_Noun_Verb) ΛListKeyMap() (map[string]interface{}, error) {

	return map[string]interface{}{
		"verb": t.Verb,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Rbac_Rbac_RoleBinding_Noun_Verb) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Rbac_Rbac_RoleBinding_Noun_Verb"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Rbac_Rbac_RoleBinding_Noun_Verb) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }


// E_RbacIdentities_NOUNTYPE is a derived int64 type which is used to represent
// the enumerated node RbacIdentities_NOUNTYPE. An additional value named
// RbacIdentities_NOUNTYPE_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_RbacIdentities_NOUNTYPE int64

// IsYANGGoEnum ensures that RbacIdentities_NOUNTYPE implements the yang.GoEnum
// interface. This ensures that RbacIdentities_NOUNTYPE can be identified as a
// mapped type for a YANG enumeration.
func (E_RbacIdentities_NOUNTYPE) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  RbacIdentities_NOUNTYPE.
func (E_RbacIdentities_NOUNTYPE) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

const (
	// RbacIdentities_NOUNTYPE_UNSET corresponds to the value UNSET of RbacIdentities_NOUNTYPE
	RbacIdentities_NOUNTYPE_UNSET E_RbacIdentities_NOUNTYPE = 0
	// RbacIdentities_NOUNTYPE_CONFIG corresponds to the value CONFIG of RbacIdentities_NOUNTYPE
	RbacIdentities_NOUNTYPE_CONFIG E_RbacIdentities_NOUNTYPE = 1
	// RbacIdentities_NOUNTYPE_GRPC corresponds to the value GRPC of RbacIdentities_NOUNTYPE
	RbacIdentities_NOUNTYPE_GRPC E_RbacIdentities_NOUNTYPE = 2
)


// E_RbacIdentities_VERB is a derived int64 type which is used to represent
// the enumerated node RbacIdentities_VERB. An additional value named
// RbacIdentities_VERB_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_RbacIdentities_VERB int64

// IsYANGGoEnum ensures that RbacIdentities_VERB implements the yang.GoEnum
// interface. This ensures that RbacIdentities_VERB can be identified as a
// mapped type for a YANG enumeration.
func (E_RbacIdentities_VERB) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  RbacIdentities_VERB.
func (E_RbacIdentities_VERB) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum; }

const (
	// RbacIdentities_VERB_UNSET corresponds to the value UNSET of RbacIdentities_VERB
	RbacIdentities_VERB_UNSET E_RbacIdentities_VERB = 0
	// RbacIdentities_VERB_CREATE corresponds to the value CREATE of RbacIdentities_VERB
	RbacIdentities_VERB_CREATE E_RbacIdentities_VERB = 1
	// RbacIdentities_VERB_DELETE corresponds to the value DELETE of RbacIdentities_VERB
	RbacIdentities_VERB_DELETE E_RbacIdentities_VERB = 2
	// RbacIdentities_VERB_READ corresponds to the value READ of RbacIdentities_VERB
	RbacIdentities_VERB_READ E_RbacIdentities_VERB = 3
	// RbacIdentities_VERB_RUN corresponds to the value RUN of RbacIdentities_VERB
	RbacIdentities_VERB_RUN E_RbacIdentities_VERB = 4
	// RbacIdentities_VERB_UPDATE corresponds to the value UPDATE of RbacIdentities_VERB
	RbacIdentities_VERB_UPDATE E_RbacIdentities_VERB = 5
)


// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_RbacIdentities_NOUNTYPE": {
		1: {Name: "CONFIG", DefiningModule: "rbac-identities"},
		2: {Name: "GRPC", DefiningModule: "rbac-identities"},
	},
	"E_RbacIdentities_VERB": {
		1: {Name: "CREATE", DefiningModule: "rbac-identities"},
		2: {Name: "DELETE", DefiningModule: "rbac-identities"},
		3: {Name: "READ", DefiningModule: "rbac-identities"},
		4: {Name: "RUN", DefiningModule: "rbac-identities"},
		5: {Name: "UPDATE", DefiningModule: "rbac-identities"},
	},
}


var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x5c, 0x5f, 0x73, 0xe2, 0x36,
		0x10, 0x7f, 0xe7, 0x53, 0x78, 0xf4, 0x98, 0x01, 0x43, 0xda, 0xe9, 0xb4, 0xe5, 0x8d, 0x04, 0x92,
		0xde, 0x5c, 0x42, 0x18, 0x9a, 0x64, 0xda, 0x72, 0x84, 0x51, 0x40, 0x70, 0x9a, 0x82, 0xcc, 0xc8,
		0xf6, 0x35, 0xb4, 0xc9, 0x77, 0xef, 0xf8, 0x0f, 0x4e, 0x1c, 0xb0, 0xbd, 0x2b, 0x19, 0xdf, 0x31,
		0xa7, 0x97, 0x1c, 0x67, 0x6b, 0xad, 0xd5, 0xee, 0xcf, 0xbb, 0xfb, 0x5b, 0xcb, 0xfe, 0xaf, 0x66,
		0x59, 0x96, 0x45, 0xfa, 0x74, 0xc5, 0x48, 0xdb, 0x22, 0x33, 0xf6, 0x85, 0x4f, 0x19, 0xa9, 0x47,
		0x47, 0x3f, 0x72, 0x31, 0x23, 0x6d, 0xeb, 0x34, 0xfe, 0xef, 0xb9, 0x23, 0xe6, 0x7c, 0x41, 0xda,
		0x56, 0x2b, 0x3e, 0xd0, 0xe5, 0x92, 0xb4, 0xad, 0xe8, 0x12, 0xe1, 0x01, 0xf9, 0x48, 0xa7, 0xa9,
		0x23, 0xa9, 0x8b, 0x87, 0x67, 0xeb, 0xe9, 0x73, 0xe9, 0x29, 0x92, 0xc3, 0xef, 0xa7, 0x4a, 0x4e,
		0x0c, 0x24, 0x9b, 0xf3, 0xa7, 0x9d, 0x39, 0x8a, 0xe6, 0x09, 0xcf, 0xff, 0xee, 0xf8, 0x72, 0xca,
		0xf6, 0xca, 0x46, 0xba, 0xb0, 0xcd, 0x3f, 0x8e, 0x0c, 0xd4, 0x21, 0xeb, 0x68, 0x9a, 0xfa, 0xfe,
		0x81, 0xbf, 0x51, 0xb7, 0x23, 0x17, 0xfe, 0x8a, 0x09, 0x8f, 0xb4, 0x2d, 0x4f, 0xfa, 0x2c, 0x63,
		0xe0, 0x9b, 0x51, 0x91, 0x56, 0x3b, 0xc3, 0x5e, 0x52, 0x47, 0x5e, 0xde, 0xad, 0xf6, 0xbd, 0x81,
		0x93, 0x13, 0x0b, 0xe9, 0xf8, 0xeb, 0xec, 0x95, 0x6c, 0x2d, 0x11, 0x0d, 0xcb, 0x50, 0x6e, 0xbf,
		0xe9, 0x0b, 0x5d, 0x00, 0x71, 0x05, 0xd4, 0x25, 0x50, 0xd7, 0xa0, 0x5d, 0x84, 0x76, 0x15, 0xc2,
		0x65, 0xfb, 0x5d, 0x97, 0xe1, 0xc2, 0x42, 0x57, 0x26, 0x03, 0x66, 0xcc, 0x9d, 0x4a, 0xbe, 0xf6,
		0xb8, 0x23, 0x8a, 0xed, 0xf0, 0x7a, 0xbf, 0xbe, 0x0a, 0x15, 0x2c, 0x2c, 0x76, 0x77, 0xab, 0x60,
		0x58, 0x91, 0xdb, 0x31, 0xee, 0xc7, 0xc2, 0x00, 0x0b, 0x07, 0x65, 0x58, 0x28, 0xc3, 0x43, 0x01,
		0x26, 0xf9, 0x70, 0x29, 0x80, 0x4d, 0x32, 0xdf, 0xed, 0x66, 0xcd, 0x70, 0xb6, 0x76, 0x3d, 0xc9,
		0xc5, 0x02, 0x62, 0xed, 0x6d, 0x20, 0xf8, 0x05, 0x30, 0xf6, 0x8a, 0x89, 0x85, 0xf7, 0x99, 0xb4,
		0xad, 0x11, 0xc8, 0x4e, 0x30, 0xff, 0x85, 0x57, 0xbe, 0xe6, 0x02, 0xec, 0x70, 0x24, 0xa8, 0x77,
		0xc4, 0xee, 0xe9, 0xd2, 0x67, 0xd9, 0xb1, 0x2f, 0x53, 0xee, 0x42, 0xd2, 0x69, 0x70, 0xaf, 0x75,
		0xf9, 0x82, 0x7b, 0x6e, 0x30, 0x31, 0x58, 0xfe, 0xa5, 0x8e, 0x30, 0x05, 0x7d, 0xaa, 0xde, 0x14,
		0xad, 0x56, 0x85, 0xc6, 0xa8, 0x95, 0x33, 0x6a, 0x5c, 0x53, 0x93, 0xcf, 0x71, 0x46, 0x94, 0x33,
		0xf9, 0x0c, 0x1e, 0x83, 0xb7, 0x02, 0x26, 0xfe, 0x9a, 0xf8, 0xfb, 0xc6, 0xd6, 0x1b, 0x2a, 0x16,
		0x0d, 0x3e, 0x63, 0xc2, 0xe3, 0x73, 0xce, 0xa4, 0x09, 0xc4, 0xdf, 0x59, 0x20, 0xfe, 0x51, 0xd1,
		0x14, 0xc7, 0x18, 0x86, 0x01, 0x78, 0x1d, 0x50, 0xcf, 0x63, 0x52, 0x80, 0x01, 0x4b, 0x46, 0xb4,
		0xf1, 0x6f, 0xa7, 0xf1, 0xd7, 0x64, 0x1c, 0xff, 0x68, 0x35, 0x7e, 0xfd, 0xf4, 0xa9, 0x31, 0xb1,
		0xc7, 0x27, 0xd0, 0xe0, 0x62, 0x3f, 0xdb, 0xf6, 0xf3, 0xe8, 0xe1, 0xe9, 0x8f, 0xb1, 0x7d, 0xf2,
		0x6c, 0x8f, 0x1e, 0x56, 0xd7, 0xe1, 0x0f, 0x7b, 0xf4, 0xb0, 0xbc, 0x1a, 0xdb, 0x27, 0xe4, 0x70,
		0xe9, 0x05, 0xc5, 0x0c, 0x3e, 0xb2, 0x4d, 0x71, 0x1a, 0x21, 0x57, 0xdc, 0xf5, 0x3a, 0x9e, 0x57,
		0x40, 0x22, 0xae, 0xb9, 0xe8, 0x2d, 0x59, 0x10, 0x18, 0x03, 0x24, 0x08, 0x7f, 0xb9, 0xcc, 0xc9,
		0x74, 0xd7, 0xf4, 0x09, 0x3e, 0xf8, 0x46, 0xce, 0x98, 0x64, 0xb3, 0xb3, 0x4d, 0x3c, 0x14, 0xb5,
		0xc4, 0x8e, 0x10, 0x8e, 0x47, 0x0b, 0xa9, 0x0d, 0x71, 0xa7, 0x9f, 0xd9, 0x8a, 0xae, 0x69, 0x18,
		0xd8, 0x48, 0x33, 0x08, 0xec, 0xd1, 0x9f, 0x3c, 0x22, 0x1b, 0x49, 0x7a, 0xd2, 0x9f, 0x7a, 0x22,
		0x8e, 0xbd, 0xc3, 0x47, 0x3a, 0x9d, 0x84, 0x7f, 0x2e, 0x43, 0xc1, 0x1a, 0xcc, 0x4b, 0x7b, 0xd4,
		0x27, 0xd2, 0x59, 0xb2, 0x62, 0xa2, 0x1d, 0x8e, 0x32, 0x3c, 0xdb, 0xf0, 0x6c, 0x53, 0xe7, 0x19,
		0x9e, 0x6d, 0xca, 0x3b, 0xc3, 0xb3, 0x0d, 0xcf, 0x2e, 0xe2, 0xd9, 0x41, 0xca, 0xc4, 0xd0, 0xec,
		0x78, 0xbc, 0x89, 0xbe, 0x26, 0xfa, 0x1a, 0x96, 0x6d, 0xc2, 0xb0, 0x61, 0xd9, 0x86, 0x65, 0x2b,
		0xb0, 0xec, 0xdc, 0x2c, 0xf2, 0x9d, 0x93, 0xec, 0x1c, 0x12, 0x9b, 0xcb, 0xb1, 0x87, 0x81, 0x9c,
		0x26, 0xc5, 0x6e, 0x3c, 0x72, 0x31, 0x0b, 0xea, 0x68, 0x10, 0xd5, 0x4e, 0x46, 0x1b, 0xca, 0x6d,
		0x28, 0xb7, 0x29, 0xfa, 0x0c, 0xe5, 0x36, 0xb5, 0x9e, 0xa1, 0xdc, 0x86, 0x72, 0x5b, 0x90, 0x47,
		0xdb, 0xc8, 0x07, 0xdb, 0x26, 0xf6, 0x9a, 0xd8, 0xfb, 0xd6, 0xd6, 0x4b, 0x46, 0xe7, 0x92, 0xcd,
		0x31, 0xc1, 0xf7, 0x67, 0x18, 0x71, 0x09, 0xcb, 0x51, 0xdb, 0x6e, 0xda, 0x76, 0xf4, 0xb8, 0xa7,
		0xb9, 0x7d, 0x22, 0x76, 0x80, 0x3b, 0x41, 0x38, 0x3e, 0xa2, 0x14, 0x09, 0x47, 0xc3, 0xee, 0x83,
		0x53, 0x73, 0x1f, 0x1c, 0xe3, 0x7d, 0x50, 0x54, 0xc2, 0xbe, 0x02, 0x27, 0x32, 0x35, 0xd0, 0x70,
		0x09, 0x80, 0x82, 0x7f, 0x81, 0x4b, 0xc7, 0x25, 0x3b, 0x30, 0xa0, 0x54, 0x80, 0xa5, 0x0a, 0x30,
		0x55, 0xa0, 0x69, 0x03, 0x4e, 0x1b, 0x78, 0x1a, 0x00, 0x44, 0x16, 0x00, 0x40, 0x6f, 0x81, 0x03,
		0xb4, 0x7a, 0x91, 0xac, 0x52, 0x2c, 0xab, 0x16, 0xcd, 0xf8, 0xe2, 0x59, 0xab, 0x88, 0xd6, 0xac,
		0x20, 0x75, 0x8b, 0xea, 0x32, 0xea, 0x49, 0x85, 0x22, 0x5b, 0xab, 0xd8, 0x2e, 0xdb, 0x64, 0x3f,
		0xb4, 0x5a, 0x5f, 0xd1, 0x68, 0xb5, 0xc3, 0x8c, 0x1e, 0x23, 0xee, 0x10, 0x6c, 0x4b, 0x36, 0x11,
		0x6c, 0xa6, 0x5a, 0xb2, 0xcd, 0xb0, 0x27, 0x0b, 0xd7, 0xb0, 0x24, 0x1a, 0x02, 0x80, 0x1d, 0xf1,
		0x30, 0x31, 0x2a, 0x89, 0x4f, 0xa1, 0x14, 0x30, 0x0a, 0x76, 0xd9, 0x9c, 0xfa, 0xcb, 0x38, 0x18,
		0xf3, 0x59, 0xfb, 0xfc, 0xa6, 0x7f, 0xf1, 0xe1, 0xd2, 0x64, 0x54, 0x93, 0x51, 0xab, 0xcc, 0xa8,
		0xd1, 0x63, 0x46, 0x6f, 0x03, 0xa3, 0x3f, 0x3b, 0x69, 0xf5, 0x27, 0x84, 0xcc, 0x87, 0x78, 0xaa,
		0x33, 0xea, 0x2a, 0x38, 0x7b, 0xab, 0x70, 0xff, 0xe6, 0xae, 0x7f, 0xfb, 0xe7, 0xa0, 0x47, 0x54,
		0x1a, 0x27, 0x2e, 0x3a, 0x62, 0xa9, 0x25, 0xf6, 0x94, 0xc6, 0x97, 0xc3, 0xc1, 0x39, 0xa9, 0x22,
		0x37, 0x6a, 0xea, 0x19, 0x07, 0xa0, 0x03, 0x27, 0xa4, 0x71, 0xe5, 0x5d, 0x27, 0x48, 0xb8, 0xff,
		0xc2, 0xe4, 0x23, 0x3e, 0xdc, 0x87, 0x52, 0xb8, 0x80, 0x7d, 0x6a, 0x02, 0xb6, 0x09, 0xd8, 0x70,
		0x6e, 0x9e, 0x08, 0x4c, 0x9d, 0x55, 0xac, 0xb7, 0x62, 0xdc, 0xdc, 0x5e, 0xa0, 0x5e, 0x49, 0x9b,
		0x1a, 0x0b, 0x5f, 0x1d, 0x18, 0xeb, 0xc2, 0x59, 0x17, 0xd6, 0xa5, 0xc1, 0xbb, 0x34, 0x98, 0x97,
		0x00, 0x77, 0x45, 0xb6, 0x81, 0xf4, 0x36, 0xba, 0x6e, 0xd1, 0xef, 0x08, 0xe8, 0x74, 0x06, 0x74,
		0x3b, 0x04, 0x7a, 0x89, 0x5a, 0xbb, 0x63, 0x50, 0x12, 0x0d, 0xde, 0xa1, 0xc3, 0xba, 0xd7, 0x29,
		0x81, 0x14, 0x6b, 0x54, 0x4d, 0xa5, 0x74, 0x16, 0x0e, 0x65, 0xda, 0xd3, 0xd6, 0xb7, 0x64, 0xdc,
		0x5a, 0x35, 0x52, 0xe3, 0x03, 0x75, 0x38, 0x30, 0xcf, 0x74, 0x51, 0x05, 0xa1, 0x4e, 0x61, 0x68,
		0x32, 0xad, 0xc9, 0xb4, 0x47, 0x91, 0x69, 0xd5, 0x3a, 0x05, 0x3a, 0x1d, 0x83, 0x72, 0x3a, 0x07,
		0x3b, 0x0b, 0xb9, 0xef, 0x0d, 0xcf, 0x88, 0x4e, 0x07, 0xd8, 0x55, 0x4e, 0xfc, 0x7a, 0xc9, 0x3f,
		0xb5, 0x8a, 0x61, 0xaf, 0xd3, 0x25, 0x5f, 0x23, 0x4f, 0x96, 0xa4, 0xff, 0xdd, 0xa0, 0xdb, 0xb9,
		0xed, 0x1d, 0xf3, 0x0a, 0x86, 0x77, 0xfd, 0x63, 0x56, 0xff, 0x7c, 0xd8, 0x3b, 0x72, 0x07, 0x74,
		0x7b, 0x57, 0x3d, 0xad, 0x15, 0x28, 0x49, 0x8e, 0xbf, 0x99, 0x27, 0x36, 0xe5, 0xb6, 0x24, 0xe2,
		0xcd, 0xe4, 0x98, 0x9e, 0x16, 0x68, 0x6b, 0xf9, 0x3e, 0x0a, 0x03, 0xde, 0x3d, 0xbe, 0xaf, 0x48,
		0x57, 0x17, 0x06, 0x6d, 0x45, 0x57, 0xb5, 0x1f, 0x70, 0xab, 0xfa, 0x8e, 0x5c, 0xee, 0xd6, 0xf5,
		0xed, 0xa6, 0xf0, 0xa6, 0x70, 0x7c, 0xd1, 0x44, 0x96, 0x95, 0xb9, 0x9b, 0xdb, 0xcf, 0xa2, 0x0b,
		0x4f, 0xfa, 0x8e, 0x2f, 0x26, 0xf7, 0xc1, 0x85, 0xcb, 0x6a, 0xb7, 0x6a, 0x6d, 0x5a, 0x89, 0x51,
		0x08, 0xd8, 0x5c, 0x82, 0x43, 0x9f, 0x12, 0xea, 0x94, 0xd0, 0x86, 0x43, 0x59, 0x91, 0x3d, 0x90,
		0xa8, 0x42, 0xa0, 0x09, 0xb2, 0xa9, 0x0a, 0x0a, 0x20, 0x72, 0xa0, 0x77, 0x29, 0x71, 0x6f, 0x52,
		0x9a, 0x6d, 0x9d, 0x66, 0x5b, 0x67, 0xe5, 0xdb, 0x3a, 0x03, 0xe0, 0x35, 0xe3, 0x37, 0xb0, 0xaa,
		0x7e, 0xe9, 0xcb, 0xca, 0xfd, 0x16, 0xa6, 0x79, 0xf1, 0xab, 0xe0, 0x95, 0x2a, 0x68, 0x88, 0x03,
		0xbf, 0x07, 0x96, 0xfb, 0xdd, 0xd3, 0x82, 0x15, 0x65, 0xae, 0x64, 0xdf, 0x57, 0x5f, 0x33, 0x94,
		0x4e, 0x2b, 0xfa, 0xaa, 0x4e, 0xf4, 0x2b, 0x56, 0x28, 0x4b, 0x11, 0xc2, 0xdd, 0x0b, 0xfa, 0x37,
		0x1b, 0x3a, 0xce, 0x6e, 0x20, 0x78, 0xaf, 0x1c, 0x79, 0x7b, 0x2a, 0xa5, 0x4b, 0x37, 0xfa, 0xd8,
		0x6e, 0x34, 0x61, 0xed, 0xe5, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
		0x2b, 0x74, 0xdd, 0xb6, 0x8b, 0x57, 0x00, 0x00,
	}
)


// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
	"/rbac/role-binding/noun/type": []reflect.Type{
		reflect.TypeOf((E_RbacIdentities_NOUNTYPE)(0)),
	},
	"/rbac/role-binding/noun/verb/verb": []reflect.Type{
		reflect.TypeOf((E_RbacIdentities_VERB)(0)),
	},
}

