#!/usr/bin/env bash

go run github.com/openconfig/ygot/generator \
-path=../../../onos-helm-charts/config-models/devicesim/files/yang \
-output_file=devicesim_1_0_0/generated.go \
-package_name=devicesim_1_0_0 \
-generate_fakeroot --include_descriptions \
openconfig-interfaces@2017-07-14.yang openconfig-openflow@2017-06-01.yang \
openconfig-platform@2016-12-22.yang openconfig-system@2017-07-06.yang

sedi=(-i)
case "$(uname)" in
  Darwin*) sedi=(-i "")
esac

lf=$'\n'; sed "${sedi[@]}" -e "1s/^/\/\/ Code generated by YGOT. DO NOT EDIT.\\$lf/" devicesim_1_0_0/generated.go


