#!/usr/bin/env bash

mkdir -p aether_5_0_0

OPENCORD="${OPENCORD:-$HOME/git/opencord}"

go run github.com/openconfig/ygot/generator -path=$OPENCORD/roc-helm-charts//config-models/aether-4.x/files/yang \
       -output_file=aether_5_0_0/generated.go -package_name=aether_5_0_0 -generate_fakeroot --include_descriptions\
       onf-enterprise.yang onf-connectivity-service.yang \
       onf-aether-types.yang onf-application.yang onf-device-group.yang onf-ip-domain.yang \
       onf-site.yang onf-upf.yang onf-template.yang onf-vcs.yang \
       onf-traffic-class.yang


sedi=(-i)
case "$(uname)" in
  Darwin*) sedi=(-i "")
esac

lf=$'\n'; sed "${sedi[@]}" -e "1s/^/\/\/ Code generated by YGOT. DO NOT EDIT.\\$lf/" aether_5_0_0/generated.go
